= Upgrade to OpenShift 4.14 / Administrator Acknowledgment
:page-aliases: how-tos/update_maintenance/v_4_12.adoc

OpenShift Container Platform 4.14 uses Kubernetes 1.27, which removed some of the deprecated `v1beta1` APIs.
A manual acknowledgment must be provided before the cluster can be upgraded to 4.14.

More information can be found in the https://docs.openshift.com/container-platform/4.14/updating/preparing_for_updates/updating-cluster-prepare.html[OpenShift Documentation].

== Upgrade to 4.14

. Check requests to removed APIs
+
[source,bash]
----
kubectl get apirequestcounts \
  --as=system:admin \
  -o jsonpath='{range .items[?(@.status.removedInRelease!="")]}{.status.removedInRelease}{"\t"}{.metadata.name}{"\t"}{.status.requestCount}{"\n"}{end}'
----
+
Should print a report like the sample below.
The last column is requests in the last 24 hours.
+
[source,bash]
----
1.27    csistoragecapacities.v1beta1.storage.k8s.io     0
----
+
If you see counts `> 0` you can check from whom the API calls are originating.
+
[source,bash]
----
kubectl get apirequestcounts csistoragecapacities.v1beta1.storage.k8s.io \
  --as=system:admin \
  -o jsonpath='{range ..username}{$}{"\n"}{end}' \
  | sort | uniq
----
+
[NOTE]
====
Some services autodiscover supported APIs, notably https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/[kube-controller-manager] (`system:kube-controller-manager`) and ArgoCD (`system:serviceaccount:syn:argocd-application-controller`).
These services will show up as using deprecated APIs.
====
+
More advanced query: Show only resources with create and update requests.
+
[source,bash]
----
kubectl --as=system:admin get apirequestcount -ojson | jq '
    .items[] |
        select(
            .status.removedInRelease == "1.27" and .status.requestCount > 0
        ) |
        {
            resource: .metadata.name,
            requests: (
                reduce .status.last24h[] as $hour ({"requests": 0}; .requests += (
                    reduce $hour.byNode[]? as $node ({"requests": 0}; .requests += (
                        reduce $node.byUser[]? as $user ({"requests": 0}; .requests += (
                            reduce $user.byVerb[]? as $verb (0; . + (
                                if $verb.verb == "watch" or $verb.verb == "list" or $verb.verb == "get" then
                                    0
                                else
                                    $verb.requestCount
                                end
                            ))
                        ))
                    ).requests)
                ).requests)
            ).requests
        }
'
----

. Provide the Acknowledgment
+
[source,bash]
----
kubectl patch cm admin-acks \
  --as=system:admin \
  -n openshift-config \
  --patch '{"data":{"ack-4.13-kube-1.27-api-removals-in-4.14":"true"}}' \
  --type=merge
----

. Upgrade the cluster
+
Set the desired minor version in https://github.com/appuio/component-openshift-upgrade-controller/blob/master/docs/modules/ROOT/pages/references/parameters.adoc#cluster_versionopenshiftversion[`openshift_upgrade_controller.cluster_version.openshiftVersion.Minor`]. The ugprade controller will use this upgrade channel in the next maintenance window.
