= Upgrade to OpenShift 4.12 / Administrator Acknowledgment
:page-aliases: how-tos/update_maintenance/v_4_9.adoc

OpenShift Container Platform 4.12 uses Kubernetes 1.25, which removed a significant number of deprecated `v1beta1` APIs.
A manual acknowledgment must be provided before the cluster can be upgraded to 4.12.

More information can be found in https://access.redhat.com/articles/6955381.

== Upgrade to 4.12

. Check requests to removed APIs
+
[source,bash]
----
kubectl get apirequestcounts \
  --as=cluster-admin \
  -o jsonpath='{range .items[?(@.status.removedInRelease!="")]}{.status.removedInRelease}{"\t"}{.metadata.name}{"\t"}{.status.requestCount}{"\n"}{end}'
----
+
Should print a report like the sample below.
The last column is requests in the last 24 hours.
+
[source,bash]
----
1.25    cronjobs.v1beta1.batch  0
1.25    poddisruptionbudgets.v1beta1.policy     0
1.25    podsecuritypolicies.v1beta1.policy      462
----
+
If you see counts `> 0` you can check from whom the API calls are originating.
+
[source,bash]
----
kubectl get apirequestcounts customresourcedefinitions.v1beta1.apiextensions.k8s.io \
  --as=cluster-admin \
  -o jsonpath='{range ..username}{$}{"\n"}{end}' \
  | sort | uniq
----
+
[NOTE]
====
Some services autodiscover supported APIs, notably https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/[kube-controller-manager] (`system:kube-controller-manager`) and ArgoCD (`system:serviceaccount:syn:argocd-application-controller`).
These services will show up as using deprecated APIs.
====
+
More advanced query: Show only resources with create and update requests.
+
[source,bash]
----
kubectl --as=cluster-admin get apirequestcount -ojson | jq '
    .items[] |
        select(
            .status.removedInRelease == "1.25" and .status.requestCount > 0
        ) |
        {
            resource: .metadata.name,
            requests: (
                reduce .status.last24h[] as $hour ({"requests": 0}; .requests += (
                    reduce $hour.byNode[]? as $node ({"requests": 0}; .requests += (
                        reduce $node.byUser[]? as $user ({"requests": 0}; .requests += (
                            reduce $user.byVerb[]? as $verb (0; . + (
                                if $verb.verb == "watch" or $verb.verb == "list" or $verb.verb == "get" then
                                    0
                                else
                                    $verb.requestCount
                                end
                            ))
                        ))
                    ).requests)
                ).requests)
            ).requests
        }
'
----

. Provide the Acknowledgment
+
[source,bash]
----
kubectl patch cm admin-acks \
  --as=cluster-admin \
  -n openshift-config \
  --patch '{"data":{"ack-4.11-kube-1.25-api-removals-in-4.12":"true"}}' \
  --type=merge
----

. Upgrade the cluster
+
Follow the steps in xref:oc4:ROOT:how-tos/update_maintenance.adoc[Update/Maintenance].
