= Upgrade to OpenShift 4.9

OpenShift Container Platform 4.9 uses Kubernetes 1.22, which removed a significant number of deprecated `v1beta1` APIs.
A manual acknowledgment must be provided before the cluster can be upgraded to 4.9.

More information can be found in https://access.redhat.com/articles/6329921.

== Upgrade to 4.9

. Check requests to removed APIs
+
[source,bash]
----
kubectl get apirequestcounts \
  --as=cluster-admin \
  -o jsonpath='{range .items[?(@.status.removedInRelease!="")]}{.status.removedInRelease}{"\t"}{.metadata.name}{"\t"}{.status.requestCount}{"\n"}{end}'
----
+
Should print a report like the sample below.
The last column is requests in the last 24 hours.
+
[source,bash]
----
1.22	customresourcedefinitions.v1beta1.apiextensions.k8s.io	15
1.22	ingresses.v1beta1.extensions	619
1.22	ingresses.v1beta1.networking.k8s.io	0
----
+
If you see counts `> 0` you can check from whom the API calls are originating.
+
[source,bash]
----
kubectl get apirequestcounts customresourcedefinitions.v1beta1.apiextensions.k8s.io \
  --as=cluster-admin \
  -o jsonpath='{range ..username}{$}{"\n"}{end}' \
  | sort | uniq
----
+
[NOTE]
Some services autodiscover supported APIs, notably https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/[kube-controller-manager] (`system:kube-controller-manager`) and ArgoCD (`system:serviceaccount:syn:argocd-application-controller`).
These services will show up as using deprecated APIs.

. Provide the Acknowledgment
+
[source,bash]
----
kubectl patch cm admin-acks \
  --as=cluster-admin \
  -n openshift-config \
  --patch '{"data":{"ack-4.8-kube-1.22-api-removals-in-4.9":"true"}}' \
  --type=merge
----

. Upgrade the cluster
+
Follow the steps in xref:oc4:ROOT:how-tos/update_maintenance.adoc[Update/Maintenance].
