= Install OpenShift 4 on vSphere
:ocp-minor-version: 4.19
:k8s-minor-version: 1.32
:ocp-patch-version: {ocp-minor-version}.10
:provider: vsphere

[abstract]
--
Steps to install an OpenShift 4 cluster on VMWare vSphere.

These steps follow the https://docs.openshift.com/container-platform/latest/installing/installing_vsphere/installing-vsphere-installer-provisioned-customizations.html[Installing a cluster on vSphere] docs to set up an installer provisioned installation (IPI).
--

[NOTE]
--
The certificates created during bootstrap are only valid for 24h.
So make sure you complete these steps within 24h.
--

== Starting situation

* You already have a Project Syn Tenant and its Git repository
* You have a CCSP Red Hat login and are logged into https://console.redhat.com/openshift/install/vsphere/installer-provisioned[Red Hat Openshift Cluster Manager]
+
IMPORTANT: Don't use your personal account to login to the cluster manager for installation.
* You have credentials for the target vSphere cluster with the permissions described in the https://docs.openshift.com/container-platform/4.12/installing/installing_vsphere/installing-vsphere-installer-provisioned.html#installation-vsphere-installer-infra-requirements-account_installing-vsphere-installer-provisioned[upstream documentation].
* You want to register a new cluster in Lieutenant and are about to install Openshift 4 on vSphere

== Prerequisites

include::partial$/install/prerequisites.adoc[]
* `unzip`

== Cluster Installation

include::partial$install/register.adoc[]

=== Configure input

.vSphere API
[source,bash]
----
export VCENTER_HOSTNAME=<vcenter hostname> <1>
----
<1> The vCenter hostname must be provided without the leading `https://`.

.vSphere credentials
[source,bash]
----
export VSPHERE_USERNAME=<username> <1>
export VSPHERE_PASSWORD=<password>
----
<1> Needs to be in the form `username@domain` or `domain\username`, eg. `ds.example.com\openshiftadmin`

.vSphere resources
[source,bash]
----
export VSPHERE_CLUSTER=<cluster name>
export VSPHERE_DATACENTER=<datacenter name>
export VSPHERE_DATASTORE=<datastore name>
export VSPHERE_NETWORK=<network name>
----

.Cluster machine network
[source,bash]
----
export MACHINE_NETWORK_CIDR=<machine network cidr>
export API_VIP=<api vip>
export INGRESS_VIP=<ingress vip>
----

include::partial$install/vshn-input.adoc[]

[#_set_vault_secrets]
=== Set secrets in Vault

include::partial$connect-to-vault.adoc[]

.Store various secrets in Vault
[source,bash]
----
# Store vSphere credentials
vault kv put  clusters/kv/${TENANT_ID}/${CLUSTER_ID}/vsphere/credentials \
  username=${VSPHERE_USERNAME} \
  password=${VSPHERE_PASSWORD}

# Generate an HTTP secret for the registry
vault kv put clusters/kv/${TENANT_ID}/${CLUSTER_ID}/registry \
  httpSecret=$(LC_ALL=C tr -cd "A-Za-z0-9" </dev/urandom | head -c 128)

# Generate a master password for K8up backups
vault kv put clusters/kv/${TENANT_ID}/${CLUSTER_ID}/global-backup \
  password=$(LC_ALL=C tr -cd "A-Za-z0-9" </dev/urandom | head -c 32)

# Generate a password for the cluster object backups
vault kv put clusters/kv/${TENANT_ID}/${CLUSTER_ID}/cluster-backup \
  password=$(LC_ALL=C tr -cd "A-Za-z0-9" </dev/urandom | head -c 32)
----

include::partial$install/prepare-commodore.adoc[]

[#_configure_installer]
=== Configure the OpenShift Installer

include::partial$install/configure-installer.adoc[]

=== Establish connection to vSphere

include::partial$install/socks5-proxy.adoc[]

. Trust the vSphere CA certificate
+
.Ubuntu 22.04
[source,bash]
----
curl ${CURL_OPTS:-} -kLo vsphere-ca.zip https://"${VCENTER_HOSTNAME}"/certs/download.zip
unzip vsphere-ca.zip
for cert in certs/lin/*.0; do sudo cp $cert /usr/local/share/ca-certificates/$(basename ${cert}.crt); done
rm vsphere-ca.zip
sudo update-ca-certificates
----

. Check if the vCenter hostname resolves on the host where you plan to execute `openshift-install`
+
[source,bash]
----
vcenter_ip=$(dig +short ${VCENTER_HOSTNAME})
if [ -z "${vcenter_ip}" ]; then
  echo -e "\033[0;31m${VCENTER_HOSTNAME} doesn't resolve on your host.\033[0;0m"
else
  echo -e "\033[0;32m${VCENTER_HOSTNAME} resolves to ${vcenter_ip}.\033[0;0m"
fi
----

. If the previous step printed a red message, setup a temporary entry in `/etc/hosts` for the vCenter hostname
+
NOTE: This step assumes that you access vCenter via a management jumphost and have set `$JUMPHOST_FQDN` as shown in the info box above.
+
.Set IP for vCenter hostname in your `/etc/hosts`
[source,bash]
----
vcenter_ip=$(ssh $JUMPHOST_FQDN dig +short "$VCENTER_HOSTNAME")
sudo sh -c "echo \"\n$vcenter_ip $VCENTER_HOSTNAME\" >> /etc/hosts"
----
+
.Recheck local resolution
[source,bash]
----
vcenter_ip=$(dig +short ${VCENTER_HOSTNAME})
if [ -z "${vcenter_ip}" ]; then
  echo -e "\033[0;31m${VCENTER_HOSTNAME} doesn't resolve on your host.\033[0;0m"
else
  echo -e "\033[0;32m${VCENTER_HOSTNAME} resolves to ${vcenter_ip}.\033[0;0m"
fi
----


[#_prepare_installer]
=== Prepare the OpenShift Installer

include::partial$install/run-installer.adoc[]

=== Update Project Syn cluster config

include::partial$install/prepare-syn-config.adoc[]

=== Provision the cluster

. Run the OpenShift installer
+
[source,bash]
----
openshift-install --dir "${INSTALLER_DIR}" \
  create cluster --log-level=debug
----
+
[TIP]
====
For OpenShift 4.16 and newer, `openshift-install` spins up a local Cluster-API environment using `envtest`.

If provisioning the bootstrap and control-plane nodes isn't successful, you can access the `envtest` Kubernetes API as follows:

[source,bash]
----
export KUBECONFIG="${INSTALLER_DIR}/.clusterapi_output/envtest.kubeconfig"
kubectl get cluster -A <1>
----
<1> Should show one resource in namespace `openshift-cluster-api-guests`
====

=== Access cluster API

. Export kubeconfig
+
[source,bash]
----
export KUBECONFIG="${INSTALLER_DIR}/auth/kubeconfig"
----

. Verify API access
+
[source,bash]
----
kubectl cluster-info
----

[NOTE]
====
If the cluster API is only reachable with a SOCKS5 proxy, run the following commands instead:

[source,bash]
----
cp ${INSTALLER_DIR}/auth/kubeconfig ${INSTALLER_DIR}/auth/kubeconfig-socks5
yq eval -i '.clusters[0].cluster.proxy-url="socks5://localhost:12000"' \
    ${INSTALLER_DIR}/auth/kubeconfig-socks5
export KUBECONFIG="${INSTALLER_DIR}/auth/kubeconfig-socks5"
----
====

=== Configure registry S3 credentials

. Create secret with S3 credentials https://docs.openshift.com/container-platform/{ocp-minor-version}/registry/configuring_registry_storage/configuring-registry-storage-aws-user-infrastructure.html#registry-operator-config-resources-secret-aws_configuring-registry-storage-aws-user-infrastructure[for the registry]
+
[source,bash]
----
oc create secret generic image-registry-private-configuration-user \
  --namespace openshift-image-registry \
  --from-literal=REGISTRY_STORAGE_S3_ACCESSKEY=<TBD> \
  --from-literal=REGISTRY_STORAGE_S3_SECRETKEY=<TBD>
----
+
include::partial$install/registry-samples-operator.adoc[]

include::partial$install/finalize_part1.adoc[]

include::partial$install/finalize_part2.adoc[]

include::partial$install/post-tasks.adoc[]
