= Multiple ArgoCD Instances

== Problem

If a customer also want's to use ArgoCD for their deployment, he currently has to install ArgoCD with the same version we use and not install any CRDs.
This process needs synchronization between us and the customer, if there is a new version of ArgoCD to be rolled out.

=== Goals

* We can deploy multiple instances of ArgoCD
* No synchronization needed between us and customer, if an update needs to be rolled out


== Proposals

=== Create separate ArgoCD project and root application for customer

Using the same ArgoCD instance for managing the cluster and the customers isn't an option for various reasons:
* Separation of concerns
* Separation of responsibility / accountability

=== Make ArgoCD component multi-instance ready

Making the ArgoCD component multi-instance ready would give us the option to deploy multiple instances of ArgoCD and controlling the version and configuration.

=== Use ArgoCD operator and update ArgoCD component to use operator

Using the ArgoCD operator would release us from managing customers instances. The customer would gain the ability to deploy as many instances as he'd like without any conflict with existing deployments.

The engineering effort is higher, as we would also need to refactor the existing component to use the operator and possibly refactor steward so it also uses the operator.

This option would give us the highest degree of versatility in the future.


== Decision

Use ArgoCD operator.

Using the operator gives us the most versatility.
Implementation can be done in multiple steps, steward and component-argocd can be adopted at a later point.
When creating component-argocd-operator we need to make sure to remove 2 of the CRDs that come with the operator.

Ideally the operator should be handled by steward / component-argocd in the future.


== References

* https://argocd-operator.readthedocs.io/en/latest/install/openshift/
* https://argocd-operator.readthedocs.io/en/latest/install/manual/
* https://argocd-operator.readthedocs.io/en/latest/usage/config_management_2.0/
