= DNS Scheme

An OpenShift 4 cluster is served using the DNS scheme defined below.

`<base domain>`::

  The base domain for the cluster (input by the customer).

`<cluster id>`::

  The lieutenant cluster id of the cluster (auto generated by the lieutenant API).

`<role>`::

  Machine role. One of _master_, _infra_, _worker_ and _lb_. Other roles possible when required by the customer (special node groups for builds, GPU support etc.).

`<#>`::

  A randomly defined character sequence with four digits.

`<index>`::

  A zero indexed incrementing number.

`<cluster domain>`::

  `<cluster id>.<base domain>`

`<hostname>`::

  The fully qualified domain name of machines belonging to the cluster.

  `<role><#>.<cluster domain>`

`<external api>`::

  API URL to be used by clients external to the cluster.

  `api.<cluster domain>`

`<internal api>`::

  API URL to be used by clients internal to the cluster.

  `api_int.<cluster domain>`

`<default app domain>`::

  `*.apps.<cluster domain>`

`<etcd>`::

  `etcd-<index>.<cluster domain>`

`<etcd srv>`::

   Record of type SRV pointing to the `<etcd>` instances.

  `_etcd-server-ssl._tcp.<cluster domain>`

`<acme challenge>`::

  Record of type TXT used for validating certificates using the DNS01 method.

  `_acme-challenge.<default app domain | external api>`

[IMPORTANT]
====
The following DNS records must resolve publicly:

 * `<acme challenge>`
 * `<cluster domain>`
 * `<default app domain>`
 * `<external api>`

 Everything else must resolve at least within the clusters network.
====

.Example
====
* *.apps.c-summer-shadow-2592.example.com
* _acme-challenge.api.c-summer-shadow-2592.example.com
* _acme-challenge.apps.c-summer-shadow-2592.example.com
* _etcd-server-ssl._tcp.c-summer-shadow-2592.example.com
* api-int.c-summer-shadow-2592.example.com
* api.c-summer-shadow-2592.example.com
* etcd-0.c-summer-shadow-2592.example.com
* etcd-1.c-summer-shadow-2592.example.com
* etcd-2.c-summer-shadow-2592.example.com
* infra-454b.c-summer-shadow-2592.example.com
* infra-9031.c-summer-shadow-2592.example.com
* infra-c8f2.c-summer-shadow-2592.example.com
* lb-5f52.c-summer-shadow-2592.example.com
* lb-ba8f.c-summer-shadow-2592.example.com
* master-0e9c.c-summer-shadow-2592.example.com
* master-1a3c.c-summer-shadow-2592.example.com
* master-e976.c-summer-shadow-2592.example.com
* worker-4720.c-summer-shadow-2592.example.com
* worker-7d32.c-summer-shadow-2592.example.com
* worker-a640.c-summer-shadow-2592.example.com
====
