= Uninstallation on cloudscale.ch

[abstract]
--
Steps to remove an OpenShift 4 cluster from https://cloudscale.ch[cloudscale.ch].
--

[NOTE]
--
- The commands are idempotent and can be retried if any of the steps fail.
- In the future, this procedure will be mostly automated
--

== Prerequisites

* `docker`
* `mc` https://docs.min.io/docs/minio-client-quickstart-guide.html[Minio client] (aliased to `mc` if necessary)
* `jq`
* `yq` https://mikefarah.gitbook.io/yq[yq YAML processor]


== Cluster Decommission

. Export the following vars
+
[source,bash]
----
export CLOUDSCALE_TOKEN=<cloudscale-api-token> # From https://control.cloudscale.ch/user/api-tokens
export CLUSTER_ID=<lieutenant-cluster-id>
export TENANT_ID=<lieutenant-tenant-id>
export REGION=<region> # rma or lpg (without the zone number)
export GITLAB_TOKEN=<gitlab-api-token> # From https://git.vshn.net/-/profile/personal_access_tokens
export GITLAB_USER=<gitlab-user-name>
----

include::partial$setup_terraform.adoc[]

. Grab location of LB backups and potential Icinga2 satellite host before decommissioning VMs.
+
[source,shell]
----
declare -a LB_FQDNS
for id in 0 1; do
  LB_FQDNS[$id]=$(terraform state show "module.cluster.module.lb.cloudscale_server.lb[$(expr $id - 1)]" | grep fqdn | awk '{print $2}' | sed -e 's/"//g')
done
for lb in ${LB_FQDNS[*]}; do
  ssh "${lb}" "sudo grep 'server =' /etc/burp/burp.conf && sudo grep 'ParentZone' /etc/icinga2/constants.conf"
done
----

. Set downtimes for both LBs in https://monitoring.vshn.net[Icinga2].

. Remove APPUiO hieradata Git repository resource from Terraform state
+
[source,console]
----
terraform state rm module.cluster.module.lb.module.hiera.gitfile_checkout.appuio_hieradata
----
+
NOTE: This step is necessary to ensure the subsequent `terraform destroy` completes without errors.


. Delete resources from clouscale.ch using Terraform
+
[source,bash]
----
# The first time it will fail
terraform destroy
# Destroy a second time to delete private networks
terraform destroy
----

. After all resources are deleted we need to remove the bucket
+
[source,bash]
----
# Use already exiting bucket user
response=$(curl -sH "Authorization: Bearer ${CLOUDSCALE_TOKEN}" \
  https://api.cloudscale.ch/v1/objects-users | \
  jq -e ".[] | select(.display_name == \"${CLUSTER_ID}\")")

# configure minio client to use the bucket
mc config host add \
  "${CLUSTER_ID}" "https://objects.${REGION}.cloudscale.ch" \
  $(echo $response | jq -r '.keys[0].access_key') \
  $(echo $response | jq -r '.keys[0].secret_key')

# delete bootstrap-ignition object
mc rb "${CLUSTER_ID}/${CLUSTER_ID}-bootstrap-ignition" --force

# delete image-registry object
mc rb "${CLUSTER_ID}/${CLUSTER_ID}-image-registry" --force

# delete cloudscale.ch user object
curl -i -H "Authorization: Bearer ${CLOUDSCALE_TOKEN}" -X DELETE $(echo $response | jq -r '.href')
----

. Delete vault entries:
+
[source,bash]
----
# Vault login
export VAULT_ADDR=https://vault-prod.syn.vshn.net
vault login -method=ldap username=<your.name>

# delete token secret
vault kv delete clusters/kv/${TENANT_ID}/${CLUSTER_ID}/cloudscale

# delete registry secret
vault kv delete clusters/kv/${TENANT_ID}/${CLUSTER_ID}/registry

# delete ldap secret
vault kv delete clusters/kv/${TENANT_ID}/${CLUSTER_ID}/vshn-ldap
----

. Decommission Puppet-managed LBs according to the https://wiki.vshn.net/display/VT/How+To%3A+Decommission+a+VM[VSHN documentation] (Internal link).
+
NOTE: Don't forget to remove the LB configuration in the https://git.vshn.net/appuio/appuio_hieradata/-/tree/master/lbaas[APPUiO hieradata] and the https://git.vshn.net/vshn-puppet/nodes_hieradata[nodes hieradata].

. Delete cluster from Lieutenant API (via portal)
+
Go to https://control.vshn.net/syn/lieutenantclusters
+
- Select the Lieutenant API Endpoint
+
- Search cluster name
+
- Delete cluster entry using the delete button

. Delete LDAP service (via portal)
+
Go to https://control.vshn.net/vshn/services
+
- Search cluster name
+
- Delete cluster entry service using the delete button

. Remove IPs from LDAP allowlist
+
Edit https://git.vshn.net/vshn-puppet/vshn_hieradata/-/blob/master/corp/prod/ldap.yaml
+
- Search cluster IPs and remove those lines and any comments related.
+
- Create a Merge Request and invite a colleague for a review/approve/merge

. Delete all DNS records related with cluster (zonefiles)

. Update any related documentation
