= Install OpenShift 4 with Puppet-managed LBs on cloudscale.ch
:ocp-minor-version: 4.21
:k8s-minor-version: 1.34
:ocp-patch-version: {ocp-minor-version}.0
:workflow: cloudscale-puppet-lbs

[abstract]
--
Steps to install an OpenShift 4 cluster with Puppet-managed LBs. on https://cloudscale.ch[cloudscale.ch].

These steps follow the https://docs.openshift.com/container-platform/latest/installing/installing_bare_metal/installing-bare-metal.html[Installing a cluster on bare metal] docs to set up a user provisioned installation (UPI).
https://www.terraform.io[Terraform] is used to provision the cloud infrastructure.
--

[NOTE]
--
The commands are idempotent and can be retried if any of the steps fail.

The certificates created during bootstrap are only valid for 24h.
So make sure you complete these steps within 24h.
--

[NOTE]
====
If you're setting up a cluster that doesn't have special networking requirements, consider setting up a cluster without Puppet LBs.

See "xref:how-tos/cloudscale/install.adoc[]" for details.
====

== Starting situation

* You already have a Tenant and its git repository
* You have a CCSP Red Hat login and are logged into https://cloud.redhat.com/openshift/install/metal/user-provisioned[Red Hat Openshift Cluster Manager]
+
IMPORTANT: Don't use your personal account to login to the cluster manager for installation.
* You want to register a new cluster in Lieutenant and are about to install Openshift 4 on cloudscale.ch

== Guided Setup

include::partial$guided-setup-explanation.adoc[]

== Prerequisites

include::partial$install/prerequisites.adoc[]
* `mc` >= `RELEASE.2024-01-18T07-03-39Z` https://docs.min.io/docs/minio-client-quickstart-guide.html[Minio client] (aliased to `mc` if necessary)
* `aws` CLI https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html[Official install instructions].
You can also install the Python package with your favorite package manager (we recommend https://docs.astral.sh/uv/[`uv`]: `uv tool install awscli`).

include::partial$guided-setup/cloudscale-puppet-lbs.adoc[]
