= Installation on cloudscale.ch

[abstract]
--
Steps to install an OpenShift 4 cluster on https://cloudscale.ch[cloudscale.ch].

These steps follow the https://docs.openshift.com/container-platform/latest/installing/installing_bare_metal/installing-bare-metal.html[Installing a cluster on bare metal] docs to set up a user provisioned installation (UPI).
https://www.terraform.io[Terraform] is used to provision the cloud infrastructure.
--

[NOTE]
--
This how-to guide is still a work in progress and will change.
It's currently very specific to VSHN and needs further changes to be more generic.
--

== Prerequisites
* cloudscale.ch API token
* `terraform`
* `mc` https://docs.min.io/docs/minio-client-quickstart-guide.html[Minio client]
* `jq`
* `openshift-install` https://cloud.redhat.com/openshift/install/metal/user-provisioned[OpenShift Installer]
* Clone of the https://git.vshn.net/syn-dev/tf-poc/[tf-poc] repository


== Cluster Installation

. Register the new OpenShift 4 cluster in Lieutenant: https://control.vshn.net/syn/lieutenantclusters

. Configure input
+
[source,console]
----
export CLOUDSCALE_TOKEN=<cloudscale-api-token> # From https://control.cloudscale.ch/user/api-tokens
export GITLAB_TOKEN=<gitlab-api-token> # From https://git.vshn.net/profile/personal_access_tokens
export GITLAB_STATE_URL="https://git.vshn.net/api/v4/projects/1462/terraform/state/cloudscale1"
export REGION=rma
export CLUSTER_ID=<cluster-name>
export BASE_DOMAIN=ocp4-poc.appuio-beta.ch
export PULL_SECRET=<redhat-pull-secret> # From https://cloud.redhat.com/openshift/install/pull-secret
----

. Create S3 buckets
+
[source,console]
----
# Use already exiting bucket user
response=$(curl -H "Authorization: Bearer ${CLOUDSCALE_TOKEN}" \
  https://api.cloudscale.ch/v1/objects-users | \
  jq -e ".[] | select(.display_name == \"${CLUSTER_ID}\")")

# Or create a new one
response=$(curl -H "Authorization: Bearer ${CLOUDSCALE_TOKEN}" \
  -F display_name=${CLUSTER_ID} \
  https://api.cloudscale.ch/v1/objects-users)

mc config host add \
  s3 https://objects.${REGION}.cloudscale.ch $(echo $response | jq -r '.keys[0].access_key') $(echo $response | jq -r '.keys[0].secret_key')

mc mb --ignore-existing\
  "s3/${CLUSTER_ID}-bootstrap-ignition"
----

. Prepare git repo
+
[source,console]
----
git clone git@git.vshn.net:syn-dev/tf-poc.git

cd tf-poc

git checkout -b "setup/${CLUSTER_ID}"
----

. Prepare `install-config.yaml`
+
[source,console]
----
mkdir ${CLUSTER_ID}

cat > "${CLUSTER_ID}/install-config.yaml" <<EOF
apiVersion: v1
metadata:
  name: ${CLUSTER_ID}
baseDomain: ${BASE_DOMAIN}
compute:
  - name: worker
    replicas: 3
controlPlane:
  name: master
  replicas: 3
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
    - 172.30.0.0/16
platform:
  none: {}
pullSecret: |
  ${PULL_SECRET}
sshKey: "$(cat ~/.ssh/id_ed25519.pub)"
EOF
----

. Prepare install manifests and ignition config
+
[source,console]
----
openshift-install --dir ${CLUSTER_ID} \
  create manifests

openshift-install --dir ${CLUSTER_ID} \
  create ignition-configs

mc cp ${CLUSTER_ID}/bootstrap.ign "s3/${CLUSTER_ID}-bootstrap-ignition"

export TF_VAR_ignition_bootstrap=$(mc share download --json --expire=1h "s3/${CLUSTER_ID}-bootstrap-ignition/bootstrap.ign" | jq -r '.share')
----

. Create Terraform cluster config
+
[source,console]
----
CA_CERT=$(jq -r '.ignition.security.tls.certificateAuthorities[0].source' "${CLUSTER_ID}/master.ign" | \
  awk -F ',' '{ print $2 }' | \
  base64 --decode)

cat > "${CLUSTER_ID}.tf" <<EOF
module "${CLUSTER_ID}" {
  source = "github.com/appuio/terraform-openshift4-cloudscale?ref=module"

  cluster_id = "${CLUSTER_ID}"
  region     = "${REGION}1"

  infra_count     = 0
  master_count    = 0
  bootstrap_count = 1

  base_domain        = "${BASE_DOMAIN}"
  ssh_keys           = var.ssh_keys
  ignition_bootstrap = var.ignition_bootstrap
  infra_servers      = module.${CLUSTER_ID}.infra_servers
  ignition_ca        = <<EOL
${CA_CERT}
EOL
}

output "${CLUSTER_ID}_dns" {
  value = module.${CLUSTER_ID}.dns_entries
}
EOF
----

. Provision bootstrap node
+
[source,console]
----
terraform init \
  "-backend-config=address=${GITLAB_STATE_URL}" \
  "-backend-config=lock_address=${GITLAB_STATE_URL}/lock" \
  "-backend-config=unlock_address=${GITLAB_STATE_URL}/lock" \
  "-backend-config=username=$(whoami)" \
  "-backend-config=password=${GITLAB_TOKEN}" \
  "-backend-config=lock_method=POST" \
  "-backend-config=unlock_method=DELETE" \
  "-backend-config=retry_wait_min=5"

terraform apply
----

. Provision master nodes
+
[source,console]
----
sed -i="" '/^  master_count/d' "${CLUSTER_ID}.tf"

terraform apply
----

. Create the necessary DNS records
+
[source,console]
----
terraform output -json | jq -r ".[\"${CLUSTER_ID}_dns\"].value"
----

. Wait for bootstrap to complete
+
[source,console]
----
openshift-install --dir ${CLUSTER_ID} \
  wait-for bootstrap-complete
----

. Remove bootstrap node and provision infra nodes
+
[source,console]
----
sed -i="" '/^  bootstrap_count/d' "${CLUSTER_ID}.tf"
sed -i="" '/^  infra_count/d' "${CLUSTER_ID}.tf"

terraform apply

export KUBECONFIG=${CLUSTER_ID}/auth/kubeconfig

# Once CSRs in state Pending show up, approve them
# Needs to be run twice, two CSRs for each node need to be approved
while sleep 10; do \
  oc get csr -o go-template='{{range .items}}{{if not .status}}{{.metadata.name}}{{"\n"}}{{end}}{{end}}' | \
  xargs oc adm certificate approve; \
done

kubectl get nodes -lnode-role.kubernetes.io/worker
kubectl label node -lnode-role.kubernetes.io/worker node-role.kubernetes.io/infra=""
----

. Wait for installation to complete
+
[source,console]
----
openshift-install --dir ${CLUSTER_ID} \
  wait-for install-complete
----

. Push new cluster config
+
[source,console]
----
git add .
git commit -m "Setup cluster ${CLUSTER_ID}"
git push -u
----

. Create secret with S3 credentials https://docs.openshift.com/container-platform/4.5/registry/configuring_registry_storage/configuring-registry-storage-aws-user-infrastructure.html#registry-operator-config-resources-secret-aws_configuring-registry-storage-aws-user-infrastructure[for the registry]
+
[source,console]
----
oc create secret generic image-registry-private-configuration-user \
--namespace openshift-image-registry \
--from-literal=REGISTRY_STORAGE_S3_ACCESSKEY=${AWS_ACCESS_KEY_ID} \
--from-literal=REGISTRY_STORAGE_S3_SECRETKEY=${AWS_SECRET_ACCESS_KEY}
----

. Make the cluster Project Syn enabled
+
Install Steward on the cluster according to https://wiki.vshn.net/x/ngMBCg
+
[source,console]
----
cat ${CLUSTER_ID}/metadata.json
----
