= Storage options on Google Cloud Platform

== Read write once block disk storage

OpenShift 4 brings along a storage provisioner which taps into the disk storage offering of the Google Compute Engine.
The following storage classes are provided:

[horizontal]
standard:: Zonal standard persistent disks—Efficient and reliable block storage
regional:: Regional standard persistent disks—Efficient and reliable block storage with synchronous replication across two zones in a region
ssd:: Zonal SSD persistent disks—Fast and reliable block storage
regional-ssd:: Regional SSD persistent disks—Fast and reliable block storage with synchronous replication across two zones in a region

Check https://cloud.google.com/compute/docs/disks/[Google Compute Engine Storage Options] for the details on that storage.

Check https://cloud.google.com/compute/disks-image-pricing#disk[Google Compute Engine Disk Pricing] for the pricing of the storage options.
By default, we host clusters in Zürich (europe-west6).

[NOTE]
.Standard class
====
If a PersistentVolumeClaim doesn't request for a StorageClass explicitly, the StorageClass `standard` will be used to provision the PersistentVolume.
====

[CAUTION]
.Minimum capacity per disk
====
The Google documentation of https://cloud.google.com/compute/docs/disks/#introduction[Storage options], mentions a minimum capacity per disk.
This isn't enforced but it directly has impact on the https://developers.google.com/compute/docs/disks#performance[performace] of that disk.
====

== Related documentation

* https://v1-17.docs.kubernetes.io/docs/concepts/storage/storage-classes/#gce-pd[StorageClass options for the Google Compute Enginge Persistent Disk driver]
* https://cloud.google.com/compute/docs/disks/[Storage options of the Google Compute Engine]
* https://docs.openshift.com/container-platform/4.4/storage/persistent_storage/persistent-storage-gce.html[OpenShift 4 documentation on Google Compute Engine Persistent Disk]
* https://docs.openshift.com/container-platform/4.4/storage/understanding-persistent-storage.html[OpenShift 4 documentation on storage]
