= Disable project self-provisioning on OpenShift 4

[abstract]
This guide describes how to remove permission for users to self-provision projects on OpenShift 4 clusters.

NOTE: This how-to applies configuration that's suitable for the Espejote ManagedResource deployed by https://github.com/appuio/component-openshift4-authentication/blob/master/component/self-provisioning.libsonnet[component-openshift4-authentication].

== Prerequisites

* Access to the respective cluster's tenant repository.

== Procedure

. Checkout the target cluster's tenant repository

. Update the `openshift4-authentication` configuration to remove `system:authenticated:oauth` from `selfProvisionerGroups`:
+
[source,yaml]
----
parameters:
  openshift4_authentication:
    selfProvisionerGroups:
      - ~system:authentication:oauth <1>
----
<1> By prefixing the group name with `~`, the component removes it from the final rendered list of `selfProvisionerGroups`.
+
TIP: You can add this configuration in the tenant repo's `openshift4.yml` (or similar) if you want to disable project self-provisioning for all clusters of a tenant.

. Commit and push the change to apply it on the clusters

. Once the rollout is complete, you can verify that the change has been applied by checking who can create `projectrequests`.
+
[source,bash]
----
export KUBECONFIG=/path/to/target-cluster.kubeconfig
oc adm policy who-can create projectcrequest | grep system:authenticated:oauth <1>
----
<1> This command should produce no output if the change was applied correctly.
