:infra-type: OpenStack
:infra-svg: ocp4-architecture-openstack.svg
= APPUiO Managed OpenShift 4 on {infra-type}

== Architecture overview

include::partial$architecture/overview.adoc[]

== {infra-type} requirements

Red Hat OpenShift 4 imposes version requirements on the {infra-type} version.
See the https://docs.redhat.com/en/documentation/openshift_container_platform/latest/html/installing_on_openstack/installing-openstack-installer-custom#prerequisites[upstream documentation] for the specific version requirements as well as further details on required {infra-type} requirements.
For an overview of version compatibility, see the https://access.redhat.com/articles/4679401[OpenShift Container Platform on OpenStack Support Matrix].

APPUiO Managed OpenShift 4 needs credentials to access the {infra-type} API for three main reasons:

1. The OpenShift 4 installer needs access to {infra-type} to setup the OpenShift 4 cluster
2. OpenShift 4 manages the VMs making up the cluster from within the cluster.
3. The {infra-type} CSI driver manages additional block devices that can be used by applications



== Networking

=== Bastion host

To deploy an APPUiO Managed OpenShift 4 cluster on {infra-type}, a bastion host inside the customer's premise is required.
The bastion host:

* must be accessible via SSH from a management system operated by VSHN
* must have access to the {infra-type} API
* must have unrestricted network access to the cluster's machine network
* must run a recent Ubuntu version

The bastion host is used to run the installer from, and for troubleshooting access to both the cluster and the vCenter.
The bastion host must be provided by the {infra-type} infrastructure operator, but VSHN can handle management and maintenance.

=== Machine network

include::partial$architecture/networking-cluster.adoc[]

=== Floating IPs

To expose applications and the Kubernetes API outside the cluster, APPUiO Managed OpenShift 4 manages two floating IPs:

1. The "API VIP" for the Kubernetes and OpenShift API.
2. The "Ingress VIP" for the OpenShift Ingress Router.

APPUiO Managed OpenShift 4 runs two `keepalived` instances to manage the API and ingress VIPs through VRRP.

If applications should be exposed for non-HTTP(S) traffic (via `LoadBalancer` services), additional IPs in the machine network must be reserved to be used as VIPs.
These additional VIPs will be managed by `keepalived` instances on the cluster.

=== Pod and service networks

include::partial$architecture/networking-pods.adoc[]

=== Exposing the cluster

include::partial$architecture/networking-ingress.adoc[]

=== External services

include::partial$architecture/networking-external.adoc[]

== Storage

include::partial$architecture/storage.adoc[]

== Glossary

=== Components OpenStack

[cols="1,3,1"]
|===
|Name|Description|provided by

|Bastion host
a|A simple Ubuntu VM which is used by VSHN to bootstrap the cluster(s) and for emergency administrative access.
*Requirements*

* CPU: 2
* Memory: 4GiB
* Disk space: 20 GiB
* Connectivity:
** accessible for VSHNeers via SSH
** outgoing access to the internet
** access to the cluster machine network
** access to the {infra-type} API

|{infra-type} infrastructure operator

|{infra-type}
a|OpenStack private cloud platform.

See the upstream documentation for https://access.redhat.com/articles/4679401[supported versions], https://docs.redhat.com/en/documentation/openshift_container_platform/latest/html/installing_on_openstack/installing-openstack-installer-custom#cluster-entitlements_installing-openstack-installer-custom[network connectivity] and https://docs.redhat.com/en/documentation/openshift_container_platform/latest/html/installing_on_openstack/installing-openstack-installer-custom#prerequisites[required permissions].
|{infra-type} infrastructure operator

|Cluster machine network (sometimes "cluster network" or  "machine network")
a|An internal subnet, usually a `/24`, in which the OpenShift 4 cluster will be placed.

The terms "cluster machine network," "cluster network" and "machine network" are used interchangeably.
Only one network is required.

VMs in this network must be assigned an IP address via DHCP.
DHCP replies must include a DNS server which is reachable from the network.

Some IPs must be reserved and will be used as Virtual / Floating IPs.
OpenShift manages the floating IPs with VRRP.

At minimum two IPs must be allocated as floating IPs.
These two IPs are used for the Kubernetes API and the ingress router.

|{infra-type} infrastructure operator

|S3 compatible storage
a|Various OpenShift components require S3 compatible storage.
This storage must be provided by the customer.
On OpenStack, S3 compatible storage is enabled by Swift.

The main APPUiO Managed OpenShift 4 components that use object storage are

* OpenShift integrated image registry
* OpenShift logging stack
* APPUiO Managed cluster backups
|Customer / {infra-type} infrastructure provider

|Access gateway
|To access the OpenShift API and applications deployed on the cluster, two public IPs are required.
The following forwarding is required:

* For the ingress public IP, ports `80/tcp` and `443/tcp` must be forwarded to the "Ingress VIP" in the machine network.
* For the API public IP, port `6443/tcp` must be forwarded to the "API VIP" in the machine network.

|Customer / {infra-type} infrastructure provider

|===

=== Components General

include::partial$architecture/glossary-general.adoc[]

=== Other terms

include::partial$architecture/glossary-others.adoc[]
