:infra-type: VMWare vSphere
:infra-svg: ocp4-architecture-vsphere.svg
= APPUiO Managed OpenShift 4 on {infra-type}

== Architecture overview

include::partial$architecture/overview.adoc[]

== {infra-type} requirements

Red Hat OpenShift 4 imposes version requirements on the VMWare virtual hardware version, {infra-type} ESXi and vCenter.
See the https://docs.openshift.com/container-platform/latest/installing/installing_vsphere/installing-vsphere-installer-provisioned.html#installation-vsphere-infrastructure_installing-vsphere-installer-provisioned[upstream documentation] for the specific version requirements as well as further details on required {infra-type} requirements.

APPUiO Managed OpenShift 4 needs credentials to access the {infra-type} API for three main reasons:

1. The OpenShift 4 installer needs access to {infra-type} to setup the OpenShift 4 cluster
+
NOTE: The installer also needs to be able to access at least one ESXi host to upload the VM template from which all the cluster VMs will be created.
2. OpenShift 4 manages the VMs making up the cluster from within the cluster.
3. The {infra-type} CSI driver manages additional block devices that can be used by applications

The upstream OpenShift 4 documentation has detailed informations about the https://docs.openshift.com/container-platform/latest/installing/installing_vsphere/installing-vsphere-installer-provisioned.html#installation-vsphere-installer-infra-requirements_installing-vsphere-installer-provisioned[required permissions on {infra-type}].

NOTE: Entries for "{infra-type} CSI Driver Operator" are required.

== Networking

=== Bastion host

To deploy an APPUiO Managed OpenShift 4 cluster on {infra-type}, a bastion host inside the customer's premise is required.
The bastion host:

* must be accessible via SSH from a management system operated by VSHN
* must have access to the vCenter API
* must have access to at least one ESXi host to import the RHCOS VM template
* must have unrestricted network access to the cluster's machine network
* must run a recent Ubuntu version

The bastion host is used to run the installer from, and for troubleshooting access to both the cluster and the vCenter.
The bastion host must be provided by the {infra-type} infrastructure operator, but VSHN can handle management and maintenance.

=== Machine network

include::partial$architecture/networking-cluster.adoc[]

=== Virtual IPs

To expose applications and the Kubernetes API outside the cluster, APPUiO Managed OpenShift 4 manages two floating IPs:

1. The "API VIP" for the Kubernetes and OpenShift API.
APPUiO Managed OpenShift 4 uses `.10` in the machine network as the API VIP.
2. The "Ingress VIP" for the OpenShift Ingress Router
APPUiO Managed OpenShift 4 uses `.11` in the machine network as the Ingress VIP.

APPUiO Managed OpenShift 4 runs two `keepalived` instances to manage the API and ingress VIPs through VRRP.

If applications should be exposed for non-HTTP(S) traffic (via `LoadBalancer` services), additional IPs in the machine network must be reserved to be used as VIPs.
These additional VIPs will be managed by `keepalived` instances on the cluster.

=== Pod and service networks

include::partial$architecture/networking-pod.adoc[]

=== Exposing the cluster

The {infra-type} infrastructure operator must provide some form of ingress and egress gateway for the cluster.
The ingress gateway must expose two public IPs:

1. A public IP for the API.
Traffic to port `6443/tcp` on this IP must be forwarded to the "API VIP" in the machine network.
The forwarding of this traffic must happen transparently.
In particular, no TLS interception can be performed as the Kubernetes API depends on mutual TLS authentication.
VSHN will manage a DNS record pointing to this IP.
2. A public IP for HTTP(s) ingress.
Traffic to ports `80/tcp` and `443/tcp` on this IP must be forwarded to the "Ingress VIP" in the machine network.
The PROXY protocol should be enabled to preserve source IPs.
Forwarding should happen transparently in TCP mode.
VSHN will manage a wildcard DNS record pointing to this IP.
Additional DNS records can be pointed to this IP by the customer.

=== External services

include::partial$architecture/networking-external.adoc[]

== Storage

include::partial$architecture/storage.adoc[]

== Glossary

=== Components vSphere

[cols="1,3,1"]
|===
|Name|Description|provided by

|Bastion host
a|A simple Ubuntu VM which is used by VSHN to bootstrap the cluster(s) and for emergency administrative access.
*Requirements*

* CPU: 2
* Memory: 4GiB
* Disk space: 20 GiB
* Connectivity:
** accessible for VSHNeers via SSH
** outgoing access to the internet
** access to the cluster machine network
** access to the vSphere API
** access to at least one ESXi host to allow the initial VM template upload

|{infra-type} infrastructure operator

|{infra-type} & vCenter
a|VMWare virtualization platform.

See the upstream documentation for https://docs.openshift.com/container-platform/latest/installing/installing_vsphere/installing-vsphere-installer-provisioned.html#installation-vsphere-infrastructure_installing-vsphere-installer-provisioned[supported versions], https://docs.openshift.com/container-platform/latest/installing/installing_vsphere/installing-vsphere-installer-provisioned.html#installation-vsphere-installer-network-requirements_installing-vsphere-installer-provisioned[network connectivity] and https://docs.openshift.com/container-platform/latest/installing/installing_vsphere/installing-vsphere-installer-provisioned.html#installation-vsphere-installer-infra-requirements_installing-vsphere-installer-provisioned[required permissions].

Entries for "{infra-type} CSI Driver Operator" are required.
|{infra-type} infrastructure operator

|Cluster machine network (sometimes "cluster network" or  "machine network")
a|An internal subnet, usually a `/24`, in which the OpenShift 4 cluster will be placed.

The terms "cluster machine network," "cluster network" and "machine network" are used interchangeably.
Only one network is required.

VMs in this network must be assigned an IP address via DHCP.
DHCP replies must include a DNS server which is reachable from the network.

Some IPs must be reserved and will be used as Virtual / Floating IPs.
OpenShift manages the floating IPs with VRRP.

At minimum two IPs must be allocated as floating IPs.
These two IPs are used for the Kubernetes API and the ingress router.

|{infra-type} infrastructure operator

|S3 compatible storage
a|Various OpenShift components require S3 compatible storage.
This storage must be provided by the customer.

The main APPUiO Managed OpenShift 4 components that use object storage are

* OpenShift integrated image registry
* OpenShift logging stack
* APPUiO Managed cluster backups
|Customer / {infra-type} infrastructure provider

|Access gateway
|To access the OpenShift API and applications deployed on the cluster, two public IPs are required.
The following forwarding is required:

* For the ingress public IP, ports `80/tcp` and `443/tcp` must be forwarded to the "Ingress VIP" in the machine network.
* For the API public IP, port `6443/tcp` must be forwarded to the "API VIP" in the machine network.

|Customer / {infra-type} infrastructure provider

|===

=== Components General

include::partial$architecture/glossary-general.adoc[]

=== Other terms

include::partial$architecture/glossary-others.adoc[]
