= Uninstallation on Exoscale

[abstract]
--
Steps to remove an OpenShift 4 cluster from https://exoscale.com[Exoscale].
--

[NOTE]
--
- The commands are idempotent and can be retried if any of the steps fail.
- In the future, this procedure will be mostly automated
--

== Prerequisites

* Exoscale https://community.exoscale.com/documentation/iam/quick-start/#api-keys[API key]
* `docker`
* `jq`
* `yq` https://mikefarah.gitbook.io/yq[yq YAML processor] (version 4 or higher)
* `exo` >= v1.28.0, https://community.exoscale.com/documentation/tools/exoscale-command-line-interface[Exoscale CLI]

== Cluster Decommission

. Export the following vars
+
[source,console]
----
export EXOSCALE_ACCOUNT=<exoscale-account>
export EXOSCALE_API_KEY=<exoscale-key>
export EXOSCALE_API_SECRET=<exoscale-secret>
export EXOSCALE_REGION=<cluster-region>

export CLUSTER_ID=<cluster-name>

# From https://git.vshn.net/profile/personal_access_tokens
export GITLAB_TOKEN=<gitlab-api-token>
export GITLAB_USER=<gitlab-user-name>

# For example: https://api.syn.vshn.net
# IMPORTANT: do NOT add a trailing `/`. Commands below will fail.
export COMMODORE_API_URL=<lieutenant-api-endpoint>
export COMMODORE_API_TOKEN=<lieutenant-api-token>

export TF_VAR_lb_exoscale_api_key=irrelevant
export TF_VAR_lb_exoscale_api_secret=irrelevant
----

. Compile cluster catalog to get input variables
+
[source,console]
----
commodore catalog compile ${CLUSTER_ID}
----

. Configure Terraform secrets
+
[source,console]
----
cat <<EOF > catalog/manifests/openshift4-terraform/.env
EXOSCALE_API_KEY
EXOSCALE_API_SECRET
TF_VAR_lb_exoscale_api_key
TF_VAR_lb_exoscale_api_secret
EOF
----

include::partial$setup_terraform_exoscale.adoc[]

. Delete resources using Terraform
+
[source,console]
----
terraform destroy
----

. Use Exoscale CLI tool to empty and remove buckets
+
[source,console]
----
mkdir -p ~/.config/exoscale
cat <<EOF >> ~/.config/exoscale/exoscale.toml

[[accounts]]
  account = "${EXOSCALE_ACCOUNT}"
  defaultZone = "${EXOSCALE_REGION}"
  endpoint = "https://api.exoscale.ch/v1"
  name = "${CLUSTER_ID}"
EOF

exo storage delete -r -f "sos://${CLUSTER_ID}-bootstrap/"
exo storage rb "${CLUSTER_ID}-bootstrap"
----

[NOTE]
--
This how-to currently doesn't contain instructions to decommission the cluster in Project Syn.
If you registered the cluster in Project Syn, the places to look for data to decommission are:

* Vault
* Lieutenant
* Syn Tenant Repo
* VSHN LDAP
* LDAP IP allowlist
* Any DNS records created in VSHN DNS
--
