= Uninstallation on Exoscale

[abstract]
--
Steps to remove an OpenShift 4 cluster from https://exoscale.com[Exoscale].
--

[NOTE]
--
- The commands are idempotent and can be retried if any of the steps fail.
- In the future, this procedure will be mostly automated
--

[IMPORTANT]
--
Always follow the https://wiki.vshn.net/display/VINT/4-eye+data+deletion[4-eye data deletion] (Internal link) principle when decommissioning productive clusters.
--

== Prerequisites

* Exoscale https://community.exoscale.com/documentation/iam/quick-start/#api-keys[API key]
* `docker`
* `jq`
* `yq` https://mikefarah.gitbook.io/yq[yq YAML processor] (version 4 or higher)
* `exo` >= v1.28.0, https://community.exoscale.com/documentation/tools/exoscale-command-line-interface[Exoscale CLI]

== Cluster Decommission

. Export the following vars
+
[source,console]
----
export EXOSCALE_ACCOUNT=<exoscale-account>
export EXOSCALE_API_KEY=<exoscale-key>
export EXOSCALE_API_SECRET=<exoscale-secret>
export EXOSCALE_REGION=<cluster-region>

export CLUSTER_ID=<cluster-name>

# From https://git.vshn.net/-/profile/personal_access_tokens
export GITLAB_TOKEN=<gitlab-api-token>
export GITLAB_USER=<gitlab-user-name>

# For example: https://api.syn.vshn.net
# IMPORTANT: do NOT add a trailing `/`. Commands below will fail.
export COMMODORE_API_URL=<lieutenant-api-endpoint>
export COMMODORE_API_TOKEN=<lieutenant-api-token>

export TF_VAR_lb_exoscale_api_key=irrelevant
export TF_VAR_lb_exoscale_api_secret=irrelevant
----

. Compile cluster catalog to get input variables
+
[source,console]
----
commodore catalog compile ${CLUSTER_ID}
----

. Configure Terraform secrets
+
[source,console]
----
cat <<EOF > catalog/manifests/openshift4-terraform/.env
EXOSCALE_API_KEY
EXOSCALE_API_SECRET
TF_VAR_lb_exoscale_api_key
TF_VAR_lb_exoscale_api_secret
EOF
----

include::partial$setup_terraform.adoc[]

. Grab location of LB backups and potential Icinga2 satellite host before decommissioning VMs.
+
[source,shell]
----
declare -a LB_FQDNS
for id in 1 2; do
  LB_FQDNS[$id]=$(terraform state show module.cluster.exoscale_domain_record.lb[$(expr $id - 1)] | grep hostname | cut -d'=' -f2 | tr -d ' "\r\n')
done
for lb in ${LB_FQDNS[*]}; do
  ssh "${lb}" "sudo grep 'server =' /etc/burp/burp.conf && sudo grep 'ParentZone' /etc/icinga2/constants.conf"
done
----

. Set downtimes for both LBs in https://monitoring.vshn.net[Icinga2].

. Remove APPUiO hieradata Git repository resource from Terraform state
+
[source,console]
----
terraform state rm 'module.cluster.module.lb.module.hiera[0].gitfile_checkout.appuio_hieradata'
----
+
NOTE: This step is necessary to ensure the subsequent `terraform destroy` completes without errors.

. Delete resources using Terraform
+
[source,console]
----
terraform destroy
----

. Use Exoscale CLI tool to empty and remove buckets
+
[source,console]
----
mkdir -p ~/.config/exoscale
cat <<EOF >> ~/.config/exoscale/exoscale.toml

[[accounts]]
  account = "${EXOSCALE_ACCOUNT}"
  defaultZone = "${EXOSCALE_REGION}"
  endpoint = "https://api.exoscale.ch/v1"
  name = "${CLUSTER_ID}"
EOF

# Bootstrap bucket
exo storage delete -r -f "sos://${CLUSTER_ID}-bootstrap/"
exo storage rb -f "${CLUSTER_ID}-bootstrap"
# OpenShift Image Registry bucket
exo storage delete -r -f "sos://${CLUSTER_ID}-image-registry/"
exo storage rb -f "${CLUSTER_ID}-image-registry"
----

. Decommission Puppet-managed LBs according to the https://wiki.vshn.net/display/VT/How+To%3A+Decommission+a+VM[VSHN documentation] (Internal link).
+
NOTE: Don't forget to remove the LB configuration in the https://git.vshn.net/appuio/appuio_hieradata/-/tree/master/lbaas[APPUiO hieradata] and the https://git.vshn.net/vshn-puppet/nodes_hieradata[nodes hieradata].

. Remove cluster DNS records from VSHN DNS

. Remove cluster IPs from LDAP allowlist, if applicable

. https://kb.vshn.ch/vshnsyn/how-tos/decommission.html[Decommission cluster in Project Syn]
