= Installation on Exoscale
:ocp-minor-version: 4.20
:k8s-minor-version: 1.33
:ocp-patch-version: {ocp-minor-version}.0
:provider: exoscale
:kubectl_extra_args:

[abstract]
--
Steps to install an OpenShift 4 cluster on https://www.exoscale.com[Exoscale].

These steps follow the https://docs.openshift.com/container-platform/latest/installing/installing_bare_metal/installing-bare-metal.html[Installing a cluster on bare metal] docs to set up a user provisioned installation (UPI).
https://www.terraform.io[Terraform] is used to provision the cloud infrastructure.
--

[NOTE]
--
This how-to guide is still a work in progress and will change.
It's currently very specific to VSHN and needs further changes to be more generic.
--

NOTE: This guide is currently assuming that you're using https://github.com/appuio/terraform-openshift4-exoscale/releases/tag/v6.1.0[`terraform-openshift4-exoscale` v6] (component https://github.com/appuio/component-openshift4-terraform/releases/tag/v8.1.0[openshift4-terraform v8])

== Starting situation

* You already have a Tenant and its Git repository
* You have a CCSP Red Hat login and are logged into https://cloud.redhat.com/openshift/install/metal/user-provisioned[Red Hat Openshift Cluster Manager]
+
IMPORTANT: Don't use your personal account to login to the cluster manager for installation.
* You want to register a new cluster in Lieutenant and are about to install Openshift 4 on Exoscale

== Guided Setup

include::partial$guided-setup-explanation.adoc[]

== Prerequisites

include::partial$install/prerequisites.adoc[]
* `md5sum`
* `virt-edit`
* `cpio`
* `exo` >= v1.76.0 https://community.exoscale.com/documentation/tools/exoscale-command-line-interface[Exoscale CLI]
* An Exoscale https://community.exoscale.com/documentation/iam/quick-start/#api-keys[API key] with full permissions
* https://community.exoscale.com/documentation/dns/quick-start/#subscribing-to-the-service[DNS subscription] activated in the Exoscale organisation

[WARNING]
====
Make sure the version of openshift-install and the rhcos image is the same, otherwise ignition will fail.
====

include::partial$guided-setup/exoscale.adoc[]
