= Installation on Exoscale
:ocp-minor-version: 4.15
:k8s-minor-version: 1.28
:ocp-patch-version: {ocp-minor-version}.23
:provider: exoscale
:kubectl_extra_args:

[abstract]
--
Steps to install an OpenShift 4 cluster on https://www.exoscale.com[Exoscale].

These steps follow the https://docs.openshift.com/container-platform/latest/installing/installing_bare_metal/installing-bare-metal.html[Installing a cluster on bare metal] docs to set up a user provisioned installation (UPI).
https://www.terraform.io[Terraform] is used to provision the cloud infrastructure.
--

[NOTE]
--
This how-to guide is still a work in progress and will change.
It's currently very specific to VSHN and needs further changes to be more generic.
--

NOTE: This guide is currently assuming that you're using https://github.com/appuio/terraform-openshift4-exoscale/releases/tag/v5.0.0[`terraform-openshift4-exoscale` v5] (component https://github.com/appuio/component-openshift4-terraform/releases/tag/v7.0.1[openshift4-terraform v7])

== Starting situation

* You already have a Tenant and its Git repository
* You have a CCSP Red Hat login and are logged into https://cloud.redhat.com/openshift/install/metal/user-provisioned[Red Hat Openshift Cluster Manager]
+
IMPORTANT: Don't use your personal account to login to the cluster manager for installation.
* You want to register a new cluster in Lieutenant and are about to install Openshift 4 on Exoscale

== Prerequisites

include::partial$install/prerequisites.adoc[]
* `md5sum`
* `virt-edit`
* `cpio`
* `exo` >= v1.76.0 https://community.exoscale.com/documentation/tools/exoscale-command-line-interface[Exoscale CLI]
* An Exoscale https://community.exoscale.com/documentation/iam/quick-start/#api-keys[API key] with full permissions
* https://community.exoscale.com/documentation/dns/quick-start/#subscribing-to-the-service[DNS subscription] activated in the Exoscale organisation

[WARNING]
====
Make sure the version of openshift-install and the rhcos image is the same, otherwise ignition will fail.
====

== Cluster Installation

include::partial$install/register.adoc[]

=== Configure input

include::partial$exoscale/environment-vars.adoc[]

include::partial$install/vshn-input.adoc[]

[#_create_iam_keys]
=== Create restricted Exoscale IAM keys for the LBs and object storage

[NOTE]
====
If creating the API key fails, please retry the commands starting from the command which contains `exo iam api-key`.
It may take a second or two for the newly created role to be available to reference for an API key.
====

. Create restricted API key for Exoscale object storage
+
[source,bash]
----
# Create SOS IAM role, if it doesn't exist yet in the organization
sos_iam_role_id=$(exo iam role list -O json | \
  jq -r '.[] | select(.name=="sos-full-access") | .key')
if [ -z "${sos_iam_role_id}" ]; then
echo '{
  "default-service-strategy": "deny",
  "services": {
    "sos": {"type": "allow"}
  }
}' | \
exo iam role create sos-full-access \
  --description "Full access to object storage service" \
  --policy -
fi
# Create access key
exoscale_s3_credentials=$(exo iam api-key create -O json \
  "${CLUSTER_ID}_object_storage" sos-full-access)
export EXOSCALE_S3_ACCESSKEY=$(echo "${exoscale_s3_credentials}" | jq -r '.key')
export EXOSCALE_S3_SECRETKEY=$(echo "${exoscale_s3_credentials}" | jq -r '.secret')
----

. Create restricted API key for AppCat Provider Exoscale
+
[source,bash]
----
# Create AppCat Provider Exoscale IAM role, if it doesn't exist yet in the organization
appcat_role_id=$(exo iam role list -O json | \
  jq -r '.[] | select(.name=="appcat-provider-exoscale") | .key')
if [ -z "${appcat_role_id}" ]; then
echo '{
  "default-service-strategy": "deny",
  "services": {
    "sos": {"type": "allow"},
    "dbaas": {"type": "allow"},
    "iam": {"type": "allow"}
  }
}' | \
exo iam role create appcat-provider-exoscale \
  --description "AppCat provider role: Full access to SOS, DBaaS and IAM" \
  --policy -
fi
# Create access key
appcat_credentials=$(exo iam api-key create -O json \
  appcat-provider-exoscale appcat-provider-exoscale)
export APPCAT_ACCESSKEY=$(echo "${appcat_credentials}" | jq -r '.key')
export APPCAT_SECRETKEY=$(echo "${appcat_credentials}" | jq -r '.secret')
----

. Create restricted API key for Exoscale CSI driver
+
[source,bash]
----
# Create Exoscale CSi driver Exoscale IAM role, if it doesn't exist yet in the organization
csidriver_role_id=$(exo iam role list -O json | \
  jq -r '.[] | select(.name=="csi-driver-exoscale") | .key')
if [ -z "${csidriver_role_id}" ]; then
echo '{
  "default-service-strategy": "deny",
  "services": {
    "compute": {
      "type": "rules",
      "rules": [
        {
          "expression": "operation in ['list-zones', 'get-block-storage-volume', 'list-block-storage-volumes', 'create-block-storage-volume', 'delete-block-storage-volume', 'attach-block-storage-volume-to-instance', 'detach-block-storage-volume', 'update-block-storage-volume-labels', 'resize-block-storage-volume', 'get-block-storage-snapshot', 'list-block-storage-snapshots', 'create-block-storage-snapshot', 'delete-block-storage-snapshot']",
          "action": "allow"
        }
      ]
    }
  }
}' | \
exo iam role create csi-driver-exoscale \
  --description "Exoscale CSI Driver: Access to storage operations and zone list" \
  --policy -
fi
# Create access key
csi_credentials=$(exo iam api-key create -O json \
  csi-driver-exoscale csi-driver-exoscale)
export CSI_ACCESSKEY=$(echo "${csi_credentials}" | jq -r '.key')
export CSI_SECRETKEY=$(echo "${csi_credentials}" | jq -r '.secret')
----

. Create restricted API key for Exoscale cert-manager webhook
+
[source,bash]
----
# Create Exoscale cert-manager webhook IAM role, if it doesn't exist yet in the organization
certwebhook_role_id=$(exo iam role list -O json | \
  jq -r '.[] | select(.name=="cert-webhook-exoscale") | .key')
if [ -z "${certwebhook_role_id}" ]; then
echo '{
  "default-service-strategy": "deny",
  "services": {
    "dns": {
      "type": "rules",
      "rules": [
        {
          "action": "allow",
          "expression": "operation in ['list-dns-domain-records', 'get-dns-domain-record', 'get-operation', 'list-dns-domains', 'create-dns-domain-record', 'delete-dns-domain-record']"
        }
      ]
    }
  }
}' | \
exo iam role create cert-webhook-exoscale \
  --description "Exoscale Cert Webhook: Access to dns operations" \
  --policy -
fi
# Create access key
cert_credentials=$(exo iam api-key create -O json \
  "${CLUSTER_ID}_cert_webhook" cert-webhook-exoscale)
export CERT_ACCESSKEY=$(echo "${cert_credentials}" | jq -r '.key')
export CERT_SECRETKEY=$(echo "${cert_credentials}" | jq -r '.secret')
----


[#_bootstrap_bucket]
=== Set up S3 bucket for cluster bootstrap

. Create S3 bucket
+
[source,bash]
----
exo storage create "sos://${CLUSTER_ID}-bootstrap" --zone "${EXOSCALE_ZONE}"
----

[#_upload_coreos_image]
=== Upload Red Hat CoreOS image

. Fetch and convert the latest Red Hat CoreOS image
+
[source,bash,subs="attributes+"]
----
RHCOS_VERSION="{ocp-patch-version}"

curl -L "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/{ocp-minor-version}/${RHCOS_VERSION}/rhcos-${RHCOS_VERSION}-x86_64-openstack.x86_64.qcow2.gz" | gunzip > rhcos-${RHCOS_VERSION}.qcow2

sudo virt-edit -a rhcos-${RHCOS_VERSION}.qcow2 \
  -m /dev/sda3:/ /loader/entries/ostree-1-rhcos.conf \
  -e 's/openstack/exoscale/'

exo storage upload rhcos-${RHCOS_VERSION}.qcow2 "sos://${CLUSTER_ID}-bootstrap" --acl public-read

exo compute instance-template register "rhcos-${RHCOS_VERSION}" \
  "https://${EXOSCALE_S3_ENDPOINT}/${CLUSTER_ID}-bootstrap/rhcos-${RHCOS_VERSION}.qcow2" \
  "$(md5sum rhcos-${RHCOS_VERSION}.qcow2 | awk '{ print $1 }')" \
  --zone "${EXOSCALE_ZONE}" \
  --boot-mode uefi \
  --disable-password \
  --username core \
  --description "Red Hat Enterprise Linux CoreOS (RHCOS) ${RHCOS_VERSION}"

exo storage delete "sos://${CLUSTER_ID}-bootstrap/rhcos-${RHCOS_VERSION}.qcow2"

export RHCOS_TEMPLATE="rhcos-${RHCOS_VERSION}"
----


[#_set_vault_secrets]
=== Set secrets in Vault

include::partial$connect-to-vault.adoc[]

.Store various secrets in Vault
[source,bash]
----
# Set the Exoscale object storage API key
vault kv put clusters/kv/${TENANT_ID}/${CLUSTER_ID}/exoscale/storage_iam \
  s3_access_key=${EXOSCALE_S3_ACCESSKEY} \
  s3_secret_key=${EXOSCALE_S3_SECRETKEY}

# Generate an HTTP secret for the registry
vault kv put clusters/kv/${TENANT_ID}/${CLUSTER_ID}/registry \
  httpSecret=$(LC_ALL=C tr -cd "A-Za-z0-9" </dev/urandom | head -c 128)

# Generate a master password for K8up backups
vault kv put clusters/kv/${TENANT_ID}/${CLUSTER_ID}/global-backup \
  password=$(LC_ALL=C tr -cd "A-Za-z0-9" </dev/urandom | head -c 32)

# Generate a password for the cluster object backups
vault kv put clusters/kv/${TENANT_ID}/${CLUSTER_ID}/cluster-backup \
  password=$(LC_ALL=C tr -cd "A-Za-z0-9" </dev/urandom | head -c 32)

# Set the AppCat Provider Exoscale Credentials
vault kv put clusters/kv/${TENANT_ID}/${CLUSTER_ID}/appcat/provider-exoscale \
  access-key=${APPCAT_ACCESSKEY} \
  secret-key=${APPCAT_SECRETKEY}

# Set the CSI Driver Exoscale Credentials
vault kv put clusters/kv/${TENANT_ID}/${CLUSTER_ID}/exoscale/csi_driver \
  s3_access_key=${CSI_ACCESSKEY} \
  s3_secret_key=${CSI_SECRETKEY}

# Set the Cert Manager Webhook Credentials
vault kv put clusters/kv/${TENANT_ID}/${CLUSTER_ID}/exoscale/cert_webhook \
  s3_access_key=${CERT_ACCESSKEY} \
  s3_secret_key=${CERT_SECRETKEY}
----

include::partial$get-hieradata-token-from-vault.adoc[]

include::partial$install/prepare-commodore.adoc[]

[#_configure_installer]
=== Configure the OpenShift Installer

include::partial$install/configure-installer.adoc[]

[#_run_installer]
=== Run OpenShift Installer

include::partial$install/run-installer.adoc[]

. Upload ignition config
+
[source,bash]
----
exo storage upload "${INSTALLER_DIR}/bootstrap.ign" "sos://${CLUSTER_ID}-bootstrap" --acl public-read
----

=== Terraform Cluster Config

include::partial$install/prepare-syn-config.adoc[]

=== Provision Infrastructure

include::partial$exoscale/configure-terraform-secrets.adoc[]

include::partial$setup_terraform.adoc[]

. Provision Domain and security groups
+
[source,bash]
----
cat > override.tf <<EOF
module "cluster" {
  bootstrap_count          = 0
  lb_count                 = 0
  master_count             = 0
  infra_count              = 0
  storage_count            = 0
  worker_count             = 0
  additional_worker_groups = {}
}
EOF
terraform apply
----

. Create LB hieradata
+
[source,bash]
----
cat > override.tf <<EOF
module "cluster" {
  bootstrap_count          = 0
  master_count             = 0
  infra_count              = 0
  storage_count            = 0
  worker_count             = 0
  additional_worker_groups = {}
}
EOF
terraform apply -target "module.cluster.module.lb.module.hiera"
----

. Set up DNS NS records on parent zone using the data from the Terraform output variable `ns_records` from the previous step

. Review and merge the LB hieradata MR (listed in Terraform output `hieradata_mr`) and wait until the deploy pipeline after the merge is completed.

. Create LBs
+
[source,bash]
----
terraform apply
----

. Make LB FQDNs available for later steps
+
.Store LB FQDNs in environment
[source,bash]
----
declare -a LB_FQDNS
for id in 1 2; do
  LB_FQDNS[$id]=$(terraform state show "module.cluster.module.lb.exoscale_domain_record.lb[$(expr $id - 1)]" | grep hostname | cut -d'=' -f2 | tr -d ' "\r\n')
done
----
+
.Verify FQDNs
[source,bash]
----
for lb in "${LB_FQDNS[@]}"; do echo $lb; done
----

include::partial$install/bootstrap-lb.adoc[]

include::partial$install/bootstrap-nodes.adoc[]

. Create secret with S3 credentials https://docs.openshift.com/container-platform/{ocp-minor-version}/registry/configuring_registry_storage/configuring-registry-storage-aws-user-infrastructure.html#registry-operator-config-resources-secret-aws_configuring-registry-storage-aws-user-infrastructure[for the registry]
+
[source,bash]
----
oc create secret generic image-registry-private-configuration-user \
--namespace openshift-image-registry \
--from-literal=REGISTRY_STORAGE_S3_ACCESSKEY=${EXOSCALE_S3_ACCESSKEY} \
--from-literal=REGISTRY_STORAGE_S3_SECRETKEY=${EXOSCALE_S3_SECRETKEY}
----
+
include::partial$install/registry-samples-operator.adoc[]

include::partial$install/finalize_part1.adoc[]

include::partial$install/finalize_part2.adoc[]

include::partial$install/post-tasks.adoc[]
