= Remove a worker node (no instance pool)

:cloud_provider: exoscale
:kubectl_extra_args: --as=system:admin
:delabel_app_nodes: yes

:node-delete-list: ${NODE_TO_REMOVE}
:delete-nodes-manually: no
:delete-pvs: old_pv_names

[abstract]
--
Steps to remove a worker node of an OpenShift 4 cluster on https://www.exoscale.com[Exoscale] without instance pools.
--

== Starting situation

* You already have a OpenShift 4 cluster on Exoscale
* Your cluster doesn't use Exoscale instance pools
* You have admin-level access to the cluster
* You want to remove an existing worker node in the cluster

== High-level overview

* First we identify the correct node to remove and drain it.
* Then we remove it from Kubernetes.
* Finally we remove the associated VMs.

== Prerequisites

include::partial$exoscale/prerequisites.adoc[]

== Prepare local environment

include::partial$exoscale/setup-local-env.adoc[]

== Prepare Terraform environment

include::partial$exoscale/configure-terraform-secrets.adoc[]

include::partial$setup_terraform.adoc[]

== Drain and Remove Node

* Find the node you want to remove.
It has to be the one with the highest terraform index.
+
[source,bash]
----
# Grab JSON copy of current Terraform state
terraform state pull > .tfstate.json

export NODE_TO_REMOVE=$(jq -r \
  '.resources[] |
   select(.module=="module.cluster.module.worker" and .type=="exoscale_compute") |
   .instances[.instances|length-1] |
   .attributes.hostname' \
   .tfstate.json)
echo $NODE_TO_REMOVE
----

* If you are working on a production cluster, you need to *schedule the node drain for the next maintenance.*
* If you are working on a non-production cluster, you may *drain and remove the node immediately.*

=== Schedule node drain (production clusters)

include::partial$drain-node-scheduled.adoc[]

=== Drain and remove node immediately

include::partial$drain-node-immediately.adoc[]

== Update Cluster Config

. Update cluster config.
+
[source,bash]
----
pushd "inventory/classes/${TENANT_ID}/"

yq eval -i ".parameters.openshift4_terraform.terraform_variables.worker_count -= 1" \
  ${CLUSTER_ID}.yml
----

. Review and commit
+
[source,bash]
----

# Have a look at the file ${CLUSTER_ID}.yml.

git commit -a -m "Remove worker node from cluster ${CLUSTER_ID}"
git push

popd
----

. Compile and push cluster catalog
+
[source,bash]
----
commodore catalog compile ${CLUSTER_ID} --push -i
----

== Remove VM

include::partial$delete-node-vm.adoc[]
