= Installation on Google Cloud Platform

:toc:

[abstract]
.General Procedure
--
. Setup GCP project

  * DNS zone
  * Service Account and permissions

. Cluster setup

  * prepare installer configuration
  * run installer

. Synfection

. Post install configuration
--

== Prerequisites

* GCP project setup according to xref:how-tos/gcp/project.adoc[GCP Project Setup]
* Service Account Key (key.json)

include::partial$gcp_name_length_warning.adoc[]

TIP: https://github.com/projectsyn/purser[Purser] can be used to check if the preconditons are met.

== Required input

`<base domain>`:: The base domain used to make the cluster available.
`<cluster name>`::
The name of the cluster.
This name will be used as identifier or as part of identifiers.
It also will become a subdomain to the base domain.
`<service account key>`:: See <<how-tos/gcp/project.adoc#service-account-key, Service Account Key>>
`<region>`:: The GCP region to place the cluster. Default to `europe-west6`

== Install cluster

. Obtain the installer and pull secret

   * https://cloud.redhat.com/openshift/install/gcp/installer-provisioned
   * https://cloud.redhat.com/openshift/install/pull-secret

. Copy `<service account key>` to `~/.gcp/osServiceAccount.json`

. Create an SSH key for that cluster
+
[source,bash]
----
ssh-keygen -t rsa -b 4096 -N '' -f ~/.ssh/<cluster name> -C <cluster name>
----
+
NOTE: The key must be within the home directory to be picked up by the installer.

. Create the default installer config
+
[source,bash]
----
openshift-install create install-config --dir=<cluster name>-config <1>
----
<1> The cluster name from the inputs.
+
--
.Answers
SSH Public Key:: `~/.ssh/<cluster namme>`
Platform:: gcp
Project ID:: Will be extracted from the service account key file.
Region:: <region>
Base Domain:: <base domain>
Cluster Name:: <cluster name>
Pull Secret:: Grab from https://cloud.redhat.com/openshift/install/pull-secret.
--
+
.Credentials for Pull Secret
****
If the customer brings his own subscriptions, the customer should obtain the Pull Secret using his Red Hat account and produce us the Pull Secret.

For all the other cases:

VSHN:: https://password.vshn.net/cred/detail/2420/
****

. Review and tweak installer config
+
Use your editor of choice to review the created installer config.
Make changes where required.

. Make a copy of the installer config
+
Once the installer gets executed, the config will be consumed and deleted.
If the installer fails and another attempt must be made, a copy of the config is a good thing to have.
+
[source,bash]
----
cp -r <cluster name>-config <cluster name>
----

. Run the installer
+
[source,bash]
----
openshift-install create cluster --log-level=debug --dir=<cluster name>
----
+  
[WARNING]
====
Takes roughly 45 minutes to complete.
The installer might timeout.
This doesn't necessarily indicate a failed setup.
Waiting some more time might be enough.
====
   
. Put the `kubeadmin` credentials into password manager
+
Create a new password record.
Use `kubeadmin` as username and the password from `<cluster name>/auth/kubeadmin-password`.
Also upload `<cluster name>/auth/kubeconfig` as an attachment.
+  
.Password manager
****
VSHN:: Use https://password.vshn.net
****

. Gain access to the OpenShift/Kubernetes API
+
[source,bash]
----
export KUBECONFIG=<cluster name>/auth/kubeconfig
----

. Synfection
+
Synfect the cluster according to https://wiki.vshn.net/x/ngMBCg.
