= Common labels

== Kubernetes resource labels

We generally follow the https://syn.tools/syn/references/labels-guide.html[Project Syn labelling guide] for Kubernetes resources deployed on OpenShift 4 clusters.

== Alert labels

We use a few standard labels for alerts on OpenShift 4.
Currently the following labels have a well-defined meaning.

[cols="1,1,3"]
|===
|Label key |Label value |Description

|`syn`
|`"true"`
|Only alerts which have label `syn: "true"` are sent outside the cluster.
Any alerts which don't have label `syn: "true"` are permanently silenced by component `openshift4-monitoring`.

|`OnCall`
|`"true"`
|Alerts with label `OnCall: "true"` need to be handled proactively 24/7 on clusters which have service level _Guaranteed Availability_, see https://products.docs.vshn.ch/products/service_levels.html[the product documentation].
The label `OnCall: "true"` is used to configure alert forwarding to the VSHN on-call organization outside office hours.

|`Maintenance`
|`"true"`
|Alerts with label `Maintenance: "true"` are relevant during maintenance.
These alerts must be handled when a maintenance is in progress.
They indicate that there's an issue which is blocking the maintenance, or that some system has failed due to the maintenance.

|`syn_component`
|A Commodore component name
|This label indicates the Commodore component which manages the alert rule.
This label is intended to help engineers to find the source code where the alert rule is defined or adjusted.

|`cluster_id`
|A Project Syn cluster ID
|This label identifies the cluster from which the alert originates.
We use the cluster's Project Syn ID as a unique identifier.

|`tenant_id`
|A Project Syn tenant ID
|This label identifies the tenant which owns the cluster from which the alert originates.
We use the tenant's Project Syn ID as a unique identifier.

|===

NOTE: The `cluster_id` and `tenant_id` labels are added to all alerts (and time series) through Prometheus's https://prometheus.io/docs/prometheus/latest/configuration/configuration/#configuration-file[external labels] feature.
