= Release Notes

TIP: This page lists notable changes in OpenShift releases which we find important. Reading release notes for you as a service.

== OpenShift 4.15

OpenShift version 4.15 is available since 2024-03-19.
This version is based on Kubernetes 1.28 and CRI-O 1.28.
The RHCOS image still uses RHEL 9.2 packages.
Find the release notes in the upstream documentation at https://docs.openshift.com/container-platform/4.15/release_notes/ocp-4-15-release-notes.html[OpenShift Container Platform 4.15 release notes].
The https://www.redhat.com/en/blog/unveiling-red-hat-openshift-415[Unveiling Red Hat OpenShift 4.15] blog post is also a valuable resource.

Networking dashborads in the OpenShift console::
This release brings new dashboards to the OpenShift console, which display networking metrics.
They can be found under *Observe --> Dashboards*.
+
The new dashboards contain metrics from Linux networking, from OVN-Kubernetes, and from the Ingress Operator.
You can view low-level networking metrics as well as high-level indicators, such as HTTP error rates and latency.
+
[NOTE]
====
By default, APPUiO Managed OpenShift 4 clusters are installed with https://access.redhat.com/articles/5436171#isovalent-4[Cilium], a fully certified and supported 3rd party CNI plugin for OpenShift 4.
Therefore, the panels related to OVN-Kubernetes on the new dashboards may be empty on APPUiO Managed OpenShift 4 clusters.
====

New life cycle classification for OLM operators::
With this release, three new life cycle classifications for cluster operators are introduced:
*Platform Aligned*, for operators whose maintenance streams align with the OpenShift version;
*Platform Agnostic*, for operators who make use of maintenance streams but they don't need to align with the OpenShift version;
and *Rolling Stream*, for operators which use a single stream of rolling updates.
+
These classifications are meant to provide transparency and ease-of-understanding when preparing for cluster maintenance.

Update to CoreDNS 1.11.1::
With this release, OpenShift Container Platform is updated to CoreDNS 1.11.1.

Deprecation of the OpenShift SDN network plugin::
OpenShift SDN CNI is deprecated as of OCP 4.14.
Starting with this release, Openshift SDN is no longer an option for new installations.
In a subsequent future release, the OpenShift SDN network plugin is planned to be be removed and no longer supported.
Red Hat will provide bug fixes and support for this feature until removed, but this feature will no longer receive enhancements.
+
NOTE: New APPUiO Managed OpenShift 4 clusters are installed with https://access.redhat.com/articles/5436171#isovalent-4[Cilium], a fully certified and supported 3rd party CNI plugin for OpenShift 4.

== OpenShift 4.14

OpenShift version 4.14 is available since 2023-11-06.
This version is based on Kubernetes 1.27 and CRI-O 1.27.
The RHCOS image uses RHEL 9.2 packages.
Find the release notes in the upstream documentation as https://docs.openshift.com/container-platform/4.14/release_notes/ocp-4-14-release-notes.html[OpenShift Container Platform 4.14 release notes].
The https://www.redhat.com/en/blog/red-hat-openshift-4.14-is-now-available[Red Hat OpenShift 4.14 is now available] blog post is also a valuable resource.

API deprecations::
An API has been removed in Kubernetes 1.27.
Before updating a cluster to OpenShift 4.14, check for usage of the following API:

* `CSIStorageCapacity` Resource, `storage.k8s.io/v1beta1` migrates to `storage.k8s.io/v1`

See the upstream documentation on https://docs.openshift.com/container-platform/4.14/updating/preparing_for_updates/updating-cluster-prepare.html[preparing to update to OpenShift Container Platform 4.14] for detailed instructions to check for usage of these APIs.
If any of the APIs are used, inform the affected users and ask them to update their workloads to use the APIs indicated in the upstream documentation.


Logging in to the CLI using a web browser::
With OpenShift Container Platform 4.14, a new oc command-line interface (CLI) flag, `--web` is now available for the oc login command.
+
With this enhancement, you can log in by using a web browser, so that you don't need to insert your access token into the command line.
+
TIP: This feature has been backported to OpenShift 4.13 and can already be used on APPUiO Managed OpenShift 4 clusters.

Update to HAProxy 2.6::
With this release, OpenShift Container Platform is updated to HAProxy 2.6.

New option to deploy monitoring web console plugin resources::
With this release, the monitoring pages in the Observe section of the OpenShift Container Platform web console are deployed as a dynamic plugin.
With this change, the Cluster Monitoring Operator (CMO) is now the component that deploys the OpenShift Container Platform web console monitoring plugin resources.

New option to specify resource limits for all monitoring components::
With this release, you can now specify resource requests and limits for all monitoring components, including the following:
* Alertmanager
* kube-state-metrics
* monitoring-plugin
* node-exporter
* openshift-state-metrics
* Prometheus
* Prometheus Adapter
* Prometheus Operator and its admission webhook service
* Telemeter Client
* Thanos Querier
* Thanos Ruler
+
In previous versions of OpenShift Container Platform, you could only set options for Prometheus, Alertmanager, Thanos Querier, and Thanos Ruler.

DeploymentConfig resources are now deprecated::
As of OpenShift Container Platform 4.14, `DeploymentConfig` objects are deprecated.
`DeploymentConfig` objects are still supported, but aren't recommended for new installations.
Only security-related and critical issues will be fixed.
+
Instead, use `Deployment` objects or another alternative to provide declarative updates for pods.

Deprecation of the OpenShift SDN network plugin::
OpenShift SDN CNI is deprecated as of OpenShift Container Platform 4.14.
It's currently planned that the network plugin won't be an option for new installations in the next minor release of OpenShift Container Platform.
In a subsequent future release, the OpenShift SDN network plugin is planned to be be removed and no longer supported.
Red Hat will provide bug fixes and support for this feature until removed, but this feature will no longer receive enhancements.
As an alternative to OpenShift SDN CNI, you can use OVN Kubernetes CNI instead.
+
NOTE: New APPUiO Managed OpenShift 4 clusters are installed with https://access.redhat.com/articles/5436171#isovalent-4[Cilium], a fully certified and supported 3rd party CNI plugin for OpenShift 4.
