= Release Notes

TIP: This page lists notable changes in OpenShift releases which we find important. Reading release notes for you as a service.

== OpenShift 4.22

OpenShift version 4.22 is available since 2026-06-09.
This version is based on Kubernetes 1.35 and CRI-O 1.35.
The Red Hat CoreOS (RHCOS) image now uses RHEL 9.8 packages.

Find the full release notes in the upstream documentation at https://docs.redhat.com/en/documentation/openshift_container_platform/4.22/html/release_notes/ocp-4-22-release-notes[OpenShift Container Platform 4.22 release notes].

Mount OCI images into pods::
With OpenShift 4.22, you can mount OCI images as volumes in pods.
This enables new application patterns where large volumes of static data are distributed in a separate OCI image.

OpenShift ingress operator allows installing experimental Gateway API resources::
OpenShift 4.22 removes the restriction that prevented any install attempts of Gateway API resources belonging to the experimental channel.
This gives users more flexibility in adopting Gateway API.

OpenShift zones support for vSphere host groups::
With OpenShift 4.22, support for mapping OpenShift failure domains to vSphere host groups is generally available.
This enables seamless usage of the high availability offered by a vSphere stretched cluster configuration.

Nodes can directly boot into a custom machine config pool::
In previous OpenShift versions, worker nodes always booted into the generic `worker` machine config pool and then needed to be moved to their target machine config pool, which required an additional reboot.
With OpenShift 4.22, worker nodes can boot directly into their target machine config pool.
This removes one reboot during node provisioning.

Boot image management::
On supported infrastructures, the Machine Config Operator monitors the reported boot image version and will block cluster updates if it detects a boot image that it deems "too old."
Additionally, boot image management for worker nodes is generally available on vSphere.
This feature automatically updates the node boot image during cluster updates.

.Further notes for technical readers
[%collapsible]
====
runC container runtime is deprecated::
OpenShift 4.22 deprecates the `runc` container runtime for CRI-O.
Since all VSHN Managed OpenShift clusters use CRI-O with the default `crun` container runtime, this deprecation doesn't affect our clusters.

RHCOS 10.2 (Technology Preview)::
OpenShift 4.22 supports RHCOS 10.2 as technology preview.
We will start testing RHCOS 10 internally, but won't update any customer clusters until RHCOS 10 becomes generally available for OpenShift Container Platform.
====


== OpenShift 4.21

OpenShift version 4.21 is available since 2025-11-11.
This version is based on Kubernetes 1.34 and CRI-O 1.34.
The RHCOS image still uses RHEL 9.6 packages.
Find the release notes in the upstream documentation at https://docs.redhat.com/en/documentation/openshift_container_platform/4.21/html/release_notes/ocp-4-21-release-notes[OpenShift Container Platform 4.21 release notes].
The https://www.redhat.com/en/blog/achieve-more-red-hat-openshift-421[Achieve more with Red Hat OpenShift 4.21] blog post is also a valuable resource.

OpenShift Autoscaling gains new capabilities::
OpenShift 4.21 improves autoscaling. 
The Cluster Resource Override Operator, Cluster Autoscaler, Vertical Pod Autoscaler, and Horizontal Pod Autoscaler now include network policies that restrict Operator and operand pod traffic to explicitly allowed communication only. 
The Vertical Pod Autoscaler can also use `InPlaceOrRecreate` mode to apply resource recommendations without recreating pods where possible, falling back to pod recreation when needed. 
In addition, the Cluster Autoscaler can now be configured to cordon nodes before draining and removing them, giving administrators safer control over scale-down operations.

Linux PSI monitoring is now available::
Linux Pressure Stall Information is a kernel feature that measures how much time tasks spend stalled because they can't get CPU, memory, or I/O when they need it. 
This will be helpful to detect clusters at risk of overload, especially in shared environments.

The default `openshift` cluster image policy is now generally available::
The default `openshift` cluster image policy is now GA and enabled by default. 
Clusters upgrading from OCP 4.20 or earlier that already have a custom `ClusterImagePolicy` named `openshift` will be marked `Upgradeable=False`. 
Rename or recreate the custom policy under a different name, then remove the old openshift policy before upgrading. https://docs.redhat.com/en/documentation/openshift_container_platform/4.21/html-single/nodes/#nodes-sigstore-using[You can find more information here.]


End of support for vSphere 7::
Broadcom has ended general support for VMware vSphere 7 and VMware Cloud Foundation (VCF) 4. 
If your existing OpenShift Container Platform cluster is running on either of these platforms, you must plan to migrate or upgrade your VMware infrastructure to a supported version.
