= Release Notes

TIP: This page lists notable changes in OpenShift releases which we find important. Reading release notes for you as a service.

== OpenShift 4.11

More flexible alert routing for User Workload Monitoring::

You can now https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html#ocp-4-11-monitoring-enable-alert-routing-for-user-workload-momitoring[enable alert routing] as well as spin up a https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html#ocp-4-11-monitoring-enable-dedicated-alertmanager-for-user-defined-alerts[dedicated Alertmanager] for User Workload Monitoring. Further retention can now be defined based on https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html#ocp-4-11-monitoring-confgure-retention-size-for-metrics-storage[disk usage].

New subcommand to work with tokens::

`oc create token` replaces https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html#ocp-4-11-oc-commands-flags-tokens-deprecated[several existing commands]. Check your aliases, scripts and other convenience tools you use.

Deprecation of `snapshot.storage.k8s.io/v1beta1`::

Before update a cluster, check for usage of `snapshot.storage.k8s.io/v1beta1`. If used, inform the affected users and ask them to update to `snapshot.storage.k8s.io/v1`.

== OpenShift 4.10

The generally available version 4.10.3 got released on 2022-03-10.
The release notes are available in the upstream documentation under https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html[OpenShift Container Platform 4.10 release notes].

CSI on vShpere::
+
CSI on vShpere is now generally available but requires some https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html#ocp-4-10-installation-vsphere-csi[minimal versions of vSphere software].

Change cluster network MTU after cluster installation::
+
https://docs.openshift.com/container-platform/4.10/networking/changing-cluster-network-mtu.html[Changing the MTU for the cluster network]

Ingress Controller router compression::
+
https://docs.openshift.com/container-platform/4.10/networking/ingress-operator.html#nw-configuring-router-compression_configuring-ingress[Using router compression]

Using fsGroup to reduce pod timeouts::
+
[quote, Upstream OpenShift 4.10 Release Notes]
____
If a storage volume contains many files (~1,000,000 or greater), you may experience pod timeouts.

OpenShift Container Platform 4.10 introduces the ability to use fsGroup and fsGroupChangePolicy to skip recursive permission change for the storage volume, therefore helping to avoid pod timeout problems.
____
+
See https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html#ocp-4-10-storage-fsGroup-pod-timeouts[Using fsGroup to reduce pod timeouts].

Changed alert rule names::
+
https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html#ocp-4-10-monitoring-changes-to-alerting-rules[Some alert rules got renamed].
Check if your cluster configuration alters any of those alerts and update it accordingly.

TLS X.509 certificates must have a Subject Alternative Name::
+
[quote, Upstream OpenShift 4.10 Release Notes]
____
X.509 certificates must have a properly set the Subject Alternative Name field. If you update your cluster without this, you risk breaking your cluster or rendering it inaccessible.
____
See https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html#ocp-4-10-TLS-subject-alternative-names-required[TLS X.509 certificates must have a Subject Alternative Name].

Upgraded clusters might have insecure RBAC rules::
+
Clusters upgraded from version before 4.8 might allow unauthenticated API requests to certain resources.
Check the https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html#ocp-4-10-known-issues[OpenShift 4.10 release notes] for details on which clusters are affected.
There you will also find a snippet on how to resolve this.

== OpenShift 4.9

OpenShift 4.9 was released on 2021-10-18.
See the official release blog post https://cloud.redhat.com/blog/red-hat-openshift-4.9-is-now-generally-available[Red Hat OpenShift 4.9 Is Now Generally Available] for more information.

The release notes are available in the upstream documentation under https://docs.openshift.com/container-platform/4.9/release_notes/ocp-4-9-release-notes.html[OpenShift Container Platform 4.9 release notes].

Notable changes with a possible user-visible and operational impact:

Kubernetes 1.22 removed deprecated resource versions::
+
OpenShift 4.9 ships with Kubernetes 1.22.
Prior to Kubernetes 1.22 a bunch of resource version were marked as deprecated.
In version 1.22, those deprecated versions got removed.
Before you upgrade a cluster to OpenShift 4.9, one has to ensure that none of the deprecated resource versions are used.
If this is ignored, things might break.
See https://access.redhat.com/articles/6329921[Preparing to upgrade to OpenShift Container Platform 4.9] for more details.
+
.Administrator acknowledgment
[important]
====
Upgrade to OpenShift 4.9 requires a special administrator acknowledgment.
Check https://access.redhat.com/articles/6329921[Preparing to upgrade to OpenShift Container Platform 4.9] for instructions on how to do so.
====

Ingress controller timeout configuration parameters::
+
https://docs.openshift.com/container-platform/4.9/release_notes/ocp-4-9-release-notes.html#ocp-4-9-nw-timeout-configuration-parameters[More options to configure timeout behaviour of the ingress]

Mutual TLS Authentication::
+
https://docs.openshift.com/container-platform/4.9/release_notes/ocp-4-9-release-notes.html#ocp-4-9-nw-mutual-TLS-authentication[Mutual TLS can be offloaded to ingress]

== OpenShift 4.8

OpenShift 4.8 was released on 2021-08-02.
See the official release blog post https://cloud.redhat.com/blog/red-hat-openshift-4.8-is-now-generally-available[Red Hat OpenShift 4.8 Is Now Generally Available] for more information.

The release notes are available in the upstream documentation under https://docs.openshift.com/container-platform/4.8/release_notes/ocp-4-8-release-notes.html[OpenShift Container Platform 4.8 release notes].

Notable changes with a possible user-visible impact:

HAproxy Upgrade to 2.2::
+
[quote, Upstream OpenShift 4.8 Release Notes]
____
OpenShift Container Platform updated to HAProxy 2.2, which changes HTTP header names to lowercase by default, for example, changing `Host: xyz.com` to `host: xyz.com`. For legacy applications that are sensitive to the capitalization of HTTP header names, use the Ingress Controller `spec.httpHeaders.headerNameCaseAdjustments` API field to accommodate legacy applications until they can be fixed. Make sure to add the necessary configuration by using `spec.httpHeaders.headerNameCaseAdjustments` before upgrading OpenShift Container Platform now that HAProxy 2.2 is available.

For more information, see https://docs.openshift.com/container-platform/4.8/networking/ingress-operator.html#nw-ingress-converting-http-header-case_configuring-ingress[Converting HTTP header case].
____
+
The Commodore Component https://github.com/appuio/component-openshift4-ingress[openshift4-ingress] allows to configure the Ingress Controller like that:
+
[code]
----
parameters:
  openshift4_ingress:
    ingressControllers:
      default:
        httpHeaders:
          headerNameCaseAdjustments: true
----

Local Storage Operator::

When upgrading to OpenShift 4.8, the Local Storage Operator needs to be updated too.
The Commodore Component https://github.com/appuio/component-openshift4-local-storage[openshift4-local-storage] needs to be configured to use the new version:
+
[code]
----
parameters:
  openshift4_local_storage:
    local_storage_operator:
      channel: "4.8"
----
+
[NOTE]
====
With the introduction of Dynamic Facts this manual change won't be necessary anymore.
Please check if this change is still needed before manually pinning the channel.
====



