= Release Notes

TIP: This page lists notable changes in OpenShift releases which we find important. Reading release notes for you as a service.

== OpenShift 4.11

OpenShift version 4.11 is available since 2022-08-10.
Find the release notes at the upstream documentation as https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html[OpenShift Container Platform 4.11 release notes].
The https://cloud.redhat.com/blog/whats-new-in-red-hat-openshift-4.11[What’s New in Red Hat OpenShift 4.11] blog post is also a valuable resource.

More flexible alert routing for User Workload Monitoring::

You can now https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html#ocp-4-11-monitoring-enable-alert-routing-for-user-workload-momitoring[enable alert routing] as well as spin up a https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html#ocp-4-11-monitoring-enable-dedicated-alertmanager-for-user-defined-alerts[dedicated Alertmanager] for User Workload Monitoring.

Disk usage base metrics retention::

Metrics retention can now be defined based on https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html#ocp-4-11-monitoring-confgure-retention-size-for-metrics-storage[disk usage].

New subcommand to work with tokens::

`oc create token` replaces https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html#ocp-4-11-oc-commands-flags-tokens-deprecated[several existing commands].
Check your aliases, scripts and other convenience tools you use.

Deprecation of `snapshot.storage.k8s.io/v1beta1`::

Before update a cluster, check for usage of `snapshot.storage.k8s.io/v1beta1`.
If used, inform the affected users and ask them to update to `snapshot.storage.k8s.io/v1`.

...

From https://cloud.redhat.com/blog/whats-new-in-red-hat-openshift-4.11[the blog post] we learn:

Automatic fail-forward updates for failed operator installations::

In the context of the Operator Lifecycle Manager (OLM), a failed operator update always required manual clean up.
With OpenShift 4.11, one can enable an option to automatically recover failed updates.
If enabled and a newer patch version is available, the update gets started even if a previous update failed.

Partial updates::

OpenShift 4.11 allows updating the control plane and individual node groups individually.
They, however, must be updated all within a time window of 60 days.

Conditional updates::

OpenShift always only listed newer versions available to the cluster.
Available means, it is safe to update to that version.
OpenShift 4.11 on the Web Console no explains the risks of a certain update.
Cluster administrators can then decide to do the update anyway and accept that risk.

Web Console integrated observability::

Red Hat decided to remove the individual observability UIs.
In OpenShift 4.11 they have removed the UIs for Prometheus and Grafana.
The metrics and graphs are still available and can now be found within the OpenShift Web Console.

== OpenShift 4.10

The generally available version 4.10.3 got released on 2022-03-10.
The release notes are available in the upstream documentation under https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html[OpenShift Container Platform 4.10 release notes].

CSI on vShpere::
+
CSI on vShpere is now generally available but requires some https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html#ocp-4-10-installation-vsphere-csi[minimal versions of vSphere software].

Change cluster network MTU after cluster installation::
+
https://docs.openshift.com/container-platform/4.10/networking/changing-cluster-network-mtu.html[Changing the MTU for the cluster network]

Ingress Controller router compression::
+
https://docs.openshift.com/container-platform/4.10/networking/ingress-operator.html#nw-configuring-router-compression_configuring-ingress[Using router compression]

Using fsGroup to reduce pod timeouts::
+
[quote, Upstream OpenShift 4.10 Release Notes]
____
If a storage volume contains many files (~1,000,000 or greater), you may experience pod timeouts.

OpenShift Container Platform 4.10 introduces the ability to use fsGroup and fsGroupChangePolicy to skip recursive permission change for the storage volume, therefore helping to avoid pod timeout problems.
____
+
See https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html#ocp-4-10-storage-fsGroup-pod-timeouts[Using fsGroup to reduce pod timeouts].

Changed alert rule names::
+
https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html#ocp-4-10-monitoring-changes-to-alerting-rules[Some alert rules got renamed].
Check if your cluster configuration alters any of those alerts and update it accordingly.

TLS X.509 certificates must have a Subject Alternative Name::
+
[quote, Upstream OpenShift 4.10 Release Notes]
____
X.509 certificates must have a properly set the Subject Alternative Name field. If you update your cluster without this, you risk breaking your cluster or rendering it inaccessible.
____
See https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html#ocp-4-10-TLS-subject-alternative-names-required[TLS X.509 certificates must have a Subject Alternative Name].

Upgraded clusters might have insecure RBAC rules::
+
Clusters upgraded from version before 4.8 might allow unauthenticated API requests to certain resources.
Check the https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html#ocp-4-10-known-issues[OpenShift 4.10 release notes] for details on which clusters are affected.
There you will also find a snippet on how to resolve this.
