= Generic Pre-Install Checklist

[abstract]
To successfully install an OpenShift 4 cluster some pre-requisites are needed and some questions need to be answered before starting the installation. This page helps to be prepared for the cluster planning and installation.

== Checklist

* [ ] <<Naming and DNS>> defined?
* [ ] <<Resource requirements>> defined?
* [ ] <<Infrastructure>> defined?
* [ ] <<Network requirements>> defined?

== Naming and DNS

DNS names are very important, changing them later is usually not possible or a huge amount of (error prone) work. Plan the following points carefully:

* Base domain

Also have a look at xref:explanations/dns_scheme.adoc[DNS Scheme] to get an idea how DNS records are handled.

[TIP]
====
Consider to use DNS delegation, if the domain is owned and managed by the customer.
Once setup, this allows us to progress with the cluster setup and management without having to go back and forth with the customer.

For clusters on Exoscale the Exoscale DNS service is used.
Ask the customer to set the corresponding NS record when reaching that step within the setup.

cloudscale.ch doesn't have a DNS service.
Use the VSHN DNS server instead.
====

== Resource requirements

The main purpose of the cluster will be to run the users applications and these applications have specific resource requirements.

This needs to be taken into consideration when answering the following questions:

* What kind of virtual machines will be needed to satisfy the resource requirements (vCPU / Memory) for running the user's workload?
* How many user application Pods will be scheduled (just an estimate)?
* How many worker nodes will be needed?
* How much room for failure and maintenance (`n+1` redundancy) is needed?

Don't go below the defined minimum requirements.

Further reference:

* See infrastructure specific "Default Configuration / Minimum Requirements" for https://products.docs.vshn.ch/products/appuio/managed/ocp4.html[APPUiO Managed Red Hat OpenShift 4]
* See Red Hat's https://docs.openshift.com/container-platform/4.8/installing/installing_platform_agnostic/installing-platform-agnostic.html#minimum-resource-requirements_installing-platform-agnostic[Minimum resource requirements]

== Infrastructure

Collect the following information about the infrastructure:

* What infrastructure will be used (which cloud)?
* In which account will the cluster be installed? Gather the needed access credentials with sufficient rights.

Depending on what the infrastructure supports:

* Which region and zone(s) will be used for the cluster?
* Do the worker nodes have to be spread over multiple availability zones (AZ)?

== Network requirements

If the default network settings don't match the requirements, first answer the question "Is there really no way around using the default network settings?" - If the answer is no, prepare the following information:

[IMPORTANT]
--
The OVN-Kubernetes network provider requires the address range `100.64.0.0/16` for https://docs.openshift.com/container-platform/4.8/networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.html#considerations-migrating-ovn-kubernetes-network-provider_migrate-from-openshift-sdn[internal purposes] and can not be used.
--

* What's the IP subnet for the nodes?
* Which IP network can be used for `clusterNetwork` (SDN)? Should be a `/14`.
* Which IP network can be used for `serviceNetwork`? Should be a `/16`.

As this is a deviation from the defined default, it must be carefully designed and documented. A full network diagram is a requirement in this case.

=== Firewall requirements

Make sure the firewall requirements are met. See https://docs.openshift.com/container-platform/latest/installing/install_config/configuring-firewall.html[Configuring your firewall] and https://kb.vshn.ch/kb/vshn_infra_ips.html[VSHN Infrastructure - IP Addresses and Firewall Rules] for more details.

== Infrastructure specific Check-Lists

See the following infrastructure specific check-lists for further information:

* xref:how-tos/vsphere/pre-install-checklist.adoc[Pre-Installation Checklist for OpenShift 4 on VMware vSphere]
