= Maintenance and Update of an OpenShift 4 cluster

. Get list of available updates:
+
[source,console]
----
kubectl --as cluster-admin get clusterversion version -o json | jq '.status.availableUpdates[] | {image: .image, version: .version}'
----
       
. Update the configuration hierarchy
+
Set the following parameters to the values retrieved in the previous step:
+
* `parameters.openshift4_version.spec.desiredUpdate.image`
* `parameters.openshift4_version.spec.desiredUpdate.version`

. Compile the cluster catalog

. Enjoy the show
+
Let the OpenShift operators do their job.
+
[source,console]
----
kubectl --as cluster-admin get clusterversion version --watch
----

So far, that process just worked.
In consequence we do lack the experience on how to observe and debug.
Instruction will be added here, as soon as we gained that knowledge.
As a starting point on the process, checkout https://docs.openshift.com/container-platform/latest/updating/updating-cluster-between-minor.html[Updating a cluster between minor versions] of the OpenShift 4 documentation.

Also have a look at the blog post https://www.openshift.com/blog/the-ultimate-guide-to-openshift-release-and-upgrade-process-for-cluster-administrators[The Ultimate Guide to OpenShift Release and Upgrade Process for Cluster Administrators] which is an excellent source to understand the process.
