== Prerequisites

The following CLI utilities need to be available locally:

* `kubectl`
* `oc`
* `git`
* `jq`
* `yq`
* `vault` CLI

== Preparation

. Set downtime for the "HAProxy socket" check for the cluster's Puppet LBs in https://monitoring.vshn.net[Icinga2].

== Setup Terraform credentials

. Ensure your `KUBECONFIG` points to the target cluster
+
[source,bash]
----
kubectl cluster-info
kubectl get nodes
----

. Setup access to VSHN systems
+
include::partial$vshn-input.adoc[]

ifeval::["{provider}" == "cloudscale"]
. Extract cloudscale token from the cluster
+
[NOTE]
====
You can also fetch the token from Vault:

[source,bash]
----
export VAULT_ADDR=https://vault-prod.syn.vshn.net
vault login -method=oidc
export CLOUDSCALE_API_TOKEN=$(vault kv get -format=json \
  clusters/kv/${TENANT_ID}/${CLUSTER_ID}/cloudscale | \
  jq -r '.data.data.token')
----
====
+
[source,bash]
----
export CLOUDSCALE_API_TOKEN=$(kubectl --as=system:admin -n openshift-machine-api \
  get secret cloudscale-rw-token -ogo-template='{{.data.token|base64decode}}')
----
endif::[]
ifeval::["{provider}" == "exoscale"]
. Get an Exoscale IAM key for Terraform
+
include::partial$exoscale/environment-vars.adoc[]
endif::[]

. Compile catalog
+
[TIP]
====
We use `commodore catalog compile` here to fetch the cluster catalog.
You can also use an existing up-to-date catalog checkout.
====
+
[source,bash]
----
commodore catalog compile "${CLUSTER_ID}"
----

. Configure Terraform
+
[source,bash,subs="attributes+"]
----
cat >terraform.env <<EOF
ifeval::["{provider}" == "cloudscale"]
CLOUDSCALE_API_TOKEN
endif::[]
ifeval::["{provider}" == "exoscale"]
EXOSCALE_API_KEY
EXOSCALE_API_SECRET
endif::[]
GIT_AUTHOR_NAME
GIT_AUTHOR_EMAIL
EOF
----

include::partial$setup_terraform.adoc[]

== Replace the master node

TIP: You can repeat the steps in this section if you need to replace multiple master nodes.

. Select the master node you want to replace
+
[source,bash]
----
node=<master-XXXX>
kubectl get node "${node}"
----

. Drain the master node
+
[source,bash]
----
kubectl --as=system:admin drain --ignore-daemonsets \
  --delete-emptydir-data --force "${node}"
----

. Stop the master node
+
TIP: You can also stop the node via the {provider_link}.
+
[source,bash]
----
oc debug "node/${node}" -n syn-debug-nodes --as=system:admin \
  -- chroot /host shutdown -h now
kubectl wait --for condition=ready=unknown --timeout=600s \
  "node/${node}"
----

. Remove the master node object in the cluster
+
[source,bash]
----
kubectl --as=system:admin delete node "${node}"
----

. Remove the master node from the etcd cluster
+
IMPORTANT: As far as we know, if you don't do this step, things will go wrong later on!
+
[source,bash]
----
etcd_pod=$(kubectl -n openshift-etcd get pods -l app=etcd -oname | grep -v "${node}" | head -n1)
member_id=$(kubectl --as=system:admin -n openshift-etcd exec "${etcd_pod}" \
  -- etcdctl member list | grep "${node}" | cut -d, -f1)
kubectl --as=system:admin -n openshift-etcd exec "${etcd_pod}" \
  -- etcdctl member remove "${member_id}"
----

. Delete etcd secrets for the removed node
+
[source,bash]
----
kubectl --as=system:admin -n openshift-etcd \
  delete $(kubectl -n openshift-etcd get secrets --as=system:admin -oname | grep ${node})
----

. Remove node and id from terraform state
+
[source,bash,subs="attributes+"]
----
terraform state pull > state.json
state_index=$(jq --arg node "${node}" -r '.resources[]
  | select(.module == "module.cluster.module.master" and .type == "random_id")
  | .instances[]
  | select(.attributes.hex==$node).index_key' \
  state.json)
ifeval::["{provider}" == "cloudscale"]
terraform state rm "module.cluster.module.master.random_id.node[$state_index]"
terraform state rm "module.cluster.module.master.cloudscale_server.node[$state_index]"
endif::[]
ifeval::["{provider}" == "exoscale"]
terraform state rm "module.cluster.module.master.random_id.node_id[$state_index]"
terraform state rm "module.cluster.module.master.exoscale_compute_instance.nodes[$state_index]"
endif::[]
rm state.json
----

. Create new node via terraform
+
[source,bash]
----
terraform apply
----
ifeval::["{provider}" == "exoscale"]
+
TIP: On Exoscale, Terraform will update the `etcd-N` DNS record with the new master node IP.
endif::[]

ifeval::["{provider}" == "cloudscale"]
. Check the output of the Terraform run and update the appropriate `etcd-N` DNS record with the IP of the new master node
endif::[]

. Wait for the new master node to come online and approve CSRs
+
include::partial$install/approve-node-csrs.adoc[]

. Wait until the `etcd` and `kube-apiserver` cluster-operators are healthy again
+
IMPORTANT: It's especially important to wait here when needing to replace multiple master nodes in succession to ensure we never destroy the etcd quorum!
+
[source,bash]
----
kubectl wait --for condition=progressing=false --timeout=15m co etcd kube-apiserver
----
+
[NOTE]
====
If you're observing the etcd update, it's normal that the new etcd pod crashes initially before it gets added to the cluster correctly.
====

. Delete the old master node in the {provider_link}.

== Finalize replacement

ifeval::["{provider}" == "cloudscale"]
. Once you're done with all master nodes that need to be replaced, revert the short TTL for the `etcd-N` DNS records
endif::[]

. Double-check that you've deleted all the old nodes in the {provider_link}.

. Remove downtime for the "HAProxy socket" check for the cluster's Puppet LBs in https://monitoring.vshn.net[Icinga2].
