ifeval::["{mon-expect-to-replace-nodes}" == "yes"]
. Find the MON(s) on the node(s) to {mon-operation}
endif::[]
ifeval::["{mon-expect-to-replace-nodes}" != "yes"]
. Find the MON(s) (if any) on the node(s) to {mon-operation}
endif::[]
+
[source,bash,subs="attributes+"]
----
MON_IDS=""
for node in $(echo -n {mon-replace-list}); do
  mon_id=$(kubectl --as=cluster-admin -n syn-rook-ceph-cluster get pods \
    -lapp=rook-ceph-mon --field-selector="spec.nodeName=${node}" \
    --no-headers -ocustom-columns="MON_ID:.metadata.labels.ceph_daemon_id")
  MON_IDS="$MON_IDS $mon_id"
done
echo $MON_IDS
----
ifeval::["{mon-expect-to-replace-nodes}" != "yes"]
+
TIP: You can skip the remaining steps in this section if `$MON_ID` is empty.
endif::[]
ifeval::["{mon-expect-to-replace-nodes}" == "yes"]
+
NOTE: This step should result in a list of all the MON IDs of the cluster, since you're replacing all existing storage nodes.
endif::[]


ifeval::["{mon-argocd-autosync-already-disabled}" != "yes"]
. Disable auto sync for component `rook-ceph`.
This allows us to temporarily make manual changes to the Rook Ceph cluster.
+
include::partial$disable-argocd-autosync.adoc[]
endif::[]

. Temporarily adjust the Rook MON failover timeout.
This tells the operator to perform the MON failover after less time than the default 10 minutes.
+
[source,bash]
----
kubectl --as=cluster-admin -n syn-rook-ceph-cluster patch cephcluster cluster --type=json \
  -p '[{
    "op": "replace",
    "path": "/spec/healthCheck/daemonHealth/mon",
    "value": {
      "disabled": false,
      "interval": "10s",
      "timeout": "10s"
    }
  }]'
----

. Cordon node(s) to {mon-operation}
+
[source,bash,subs="attributes+"]
----
for node in $(echo -n {mon-replace-list}); do
  kubectl --as=cluster-admin cordon "${node}"
done
----
+
. For every id in `$MON_IDS` replace the MON pod
+
[source,bash]
----
mon_id=<MON_ID>
kubectl --as=cluster-admin -n syn-rook-ceph-cluster delete pod \
  -l app=rook-ceph-mon,ceph_daemon_id="${mon_id}"

# Wait until new MON is scheduled
kubectl --as=cluster-admin -n syn-rook-ceph-cluster get pods -w

# Wait until the cluster has regained full quorum
kubectl --as=cluster-admin -n syn-rook-ceph-cluster exec -it deploy/rook-ceph-tools -- \
  ceph status

# Repeat for all other $MON_IDS
----

. Verify that three MONs are running
+
[source,bash]
----
kubectl --as=cluster-admin -n syn-rook-ceph-cluster get deploy -l app=rook-ceph-mon
----

. Reset the MON failover timeout
+
[source,bash]
----
kubectl --as=cluster-admin -n syn-rook-ceph-cluster patch cephcluster cluster --type=json \
  -p '[{
    "op": "replace",
    "path": "/spec/healthCheck/daemonHealth/mon",
    "value": {}
  }]'
----

ifeval::["{mon-argocd-autosync-already-disabled}" != "yes"]
include::partial$enable-argocd-autosync.adoc[]
endif::[]
