ifeval::["{puppet_lbs}" != "no"]
. Decommission Puppet-managed LBs
+
TIP: See the https://vshnwiki.atlassian.net/wiki/spaces/VT/pages/8290422/How+To+Decommission+a+VM[VSHN documentation] (Internal link) for the full instructions.
+
.. Remove both LBs in https://control.vshn.net/servers/definitions/appuio[control.vshn.net]
.. Clean encdata caches
+
[source,bash]
----
for lb in ${LB_FQDNS[*]}; do
  ssh nfs1.ch1.puppet.vshn.net \
    "sudo rm /srv/nfs/export/puppetserver-puppetserver-enc-cache-pvc-*/${lb}.yaml"
done
----

.. Clean up LBs in Icinga
+
[source,bash]
----
parent_zone=$(grep "ParentZone = " ${LB_FQDNS[1]}.info | cut -d = -f2 | tr -d '" ')
if [ "$parent_zone" != "master" ]; then
  icinga_host="$parent_zone"
else
  icinga_host="master2.prod.monitoring.vshn.net"
fi

prompt="Clean up LBs in Icinga ${icinga_host}? "
if [ -n "$ZSH_VERSION" ]; then
  read -k 1 "?${prompt}"
else
  read -p "${prompt}" -n 1 -r && echo
fi
if [[ $REPLY =~ ^[Yy] ]]; then
  for lb in ${LB_FQDNS[*]}; do
    ssh "${icinga_host}" "sudo rm -rf /var/lib/icinga2/api/zones/${lb}"
  done
  if [ "$parent_zone" != "master" ]; then
    ssh "${icinga_host}" sudo puppetctl run
  fi
  ssh master2.prod.monitoring.vshn.net sudo puppetctl run
fi
----

.. Remove LBs in nodes hieradata
+
[source,bash]
----
git clone git@git.vshn.net:vshn-puppet/nodes_hieradata.git
pushd nodes_hieradata

for lb in ${LB_FQDNS[*]}; do
  git rm ${lb}.yaml
done

git commit -m"Decommission LBs for ${CLUSTER_ID}"
git push origin master

popd
----

.. Remove cluster in appuio hieradata
+
[source,bash]
----
git clone git@git.vshn.net:appuio/appuio_hieradata.git
pushd appuio_hieradata

git rm -rf lbaas/${CLUSTER_ID}*

git commit -m"Decommission ${CLUSTER_ID}"
git push origin master

popd
----

.. Delete LB backup client certs and backups on Burp server
+
[source,bash]
----
for lb in ${LB_FQDNS[*]}; do
  backup_server=$(grep "server = " ${lb}.info | cut -d= -f2 | tr -d ' ')
  ssh "$backup_server" "rm -i /var/lib/burp/CA/${lb}.crt"
  ssh "$backup_server" "rm -i /var/lib/burp/CA/${lb}.csr"
  backup="/var/lib/burp/${lb}"
  echo "$backup"
  ssh "$backup_server" "rm -rfI ${backup}"
done
----
endif::[]

. Remove cluster DNS records from VSHN DNS zonefiles
+
TIP: This step isn't necessary for clusters where the customer manages DNS.

. Delete Vault secrets for the cluster
+
[source,bash]
----
for secret in $(find catalog/refs/ -type f -printf "clusters/kv/%P\n" \
    | sed -r 's#(.*)/.*#\1#' | grep -v '__shared__/__shared__' \
    | sort -u);
do
  vault kv delete "$secret"
done
----

. Delete OpsGenie heartbeat
+
[source,bash]
----
curl "https://api.opsgenie.com/v2/heartbeats/${CLUSTER_ID}" \
  -H"Authorization: GenieKey ${OPSGENIE_KEY}" \
  -XDELETE
----

. Delete cluster from Lieutenant API (via portal)
+
Go to https://control.vshn.net/syn/lieutenantclusters
+
- Select the Lieutenant API Endpoint
+
- Search cluster name
+
- Delete cluster entry using the delete button

. Delete Keycloak service (via portal)
+
Go to https://control.vshn.net/vshn/services
+
- Search cluster name
+
- Delete cluster entry service using the delete button

. Update any related documentation
