[TIP]
====
Starting with this section, we recommend that you change into a clean directory (for example a directory in your home).
====

. Generate SSH key
+
[NOTE]
====
We generate a unique SSH key pair for the cluster as this gives us troubleshooting access.
====
+
[source,bash,subs="attributes+"]
----
SSH_PRIVATE_KEY="$(pwd)/ssh_$CLUSTER_ID"
export SSH_PUBLIC_KEY="${SSH_PRIVATE_KEY}.pub"

ssh-keygen -C "vault@$CLUSTER_ID" -t ed25519 -f $SSH_PRIVATE_KEY -N ''

BASE64_NO_WRAP='base64'
if [[ "$OSTYPE" == "linux"* ]]; then
  BASE64_NO_WRAP='base64 --wrap 0'
fi

vault kv put clusters/kv/${TENANT_ID}/${CLUSTER_ID}/{provider}/ssh \
  private_key=$(cat $SSH_PRIVATE_KEY | eval "$BASE64_NO_WRAP")

ssh-add $SSH_PRIVATE_KEY
----

. Prepare `install-config.yaml`
+
[NOTE]
--
You can add more options to the `install-config.yaml` file.
Have a look at the https://docs.openshift.com/container-platform/{ocp-minor-version}/installing/installing_bare_metal/installing-bare-metal.html#installation-bare-metal-config-yaml_installing-bare-metal[config example] for more information.

For example, you could change the SDN from a default value to something a customer requests due to some network requirements.
--
+
[source,bash]
----
export INSTALLER_DIR="$(pwd)/target"
mkdir -p "${INSTALLER_DIR}"

cat > "${INSTALLER_DIR}/install-config.yaml" <<EOF
apiVersion: v1
metadata:
  name: ${CLUSTER_ID}
baseDomain: ${BASE_DOMAIN}
platform:
  none: {}
networking:
  networkType: OVNKubernetes
pullSecret: |
  ${PULL_SECRET}
sshKey: "$(cat $SSH_PUBLIC_KEY)"
EOF
----

ifeval::["{provider}" == "cloudscale"]
+
. Cilium Optional: Add cilium
+
[%collapsible]
====
[source,bash]
----
yq eval -i '.networking.networkType = "Cilium"' "${INSTALLER_DIR}/install-config.yaml"
----

[WARNING]
If setting custom CIDR for the OpenShift networking, the corresponding values should be updated in your Commodore cluster definitions.
See https://github.com/projectsyn/component-cilium/blob/master/class/defaults.yml[Cilium Component Defaults] and https://hub.syn.tools/cilium/references/parameters.html[Parameter Reference].
Verify with `less catalog/manifests/cilium/olm/*ciliumconfig.yaml`.
====
endif::[]
