. Create wildcard cert for router
+
[source,bash]
----
kubectl get secret router-certs-default \
  -n openshift-ingress \
  -o json | \
    jq 'del(.metadata.ownerReferences) | .metadata.name = "router-certs-snakeoil"' | \
  kubectl -n openshift-ingress apply -f -
----

. Save the admin credentials in the https://password.vshn.net[password manager].
You can find the password in the file `target/auth/kubeadmin-password` and the kubeconfig in `target/auth/kubeconfig`
+
[source,bash]
----
popd
ls -l ${INSTALLER_DIR}/auth/
----

=== Enable Project Syn

. https://kb.vshn.ch/vshnsyn/how-tos/synthesize.html[Make the cluster Project Syn enabled]

=== Setup acme-dns CNAME records for the cluster

. Extract the acme-dns subdomain for the cluster after `cert-manager` has been deployed via Project Syn.
+
[source,bash]
----
fulldomain=$(kubectl -n syn-cert-manager \
  get secret acme-dns-client \
  -o jsonpath='{.data.acmedns\.json}' | \
  base64 -d  | \
  jq -r '[.[]][0].fulldomain')
echo "$fulldomain"
----

ifeval::["{provider}" == "cloudscale"]
. Add the following CNAME records to the cluster's DNS zone
+
[source,dns]
----
_acme-challenge.api  IN CNAME <fulldomain>. <1>
_acme-challenge.apps IN CNAME <fulldomain>. <1>
----
<1> Replace `<fulldomain>` with the output of the previous step.
endif::[]
ifeval::["{provider}" == "exoscale"]
. Setup the `_acme-challenge` CNAME records in the cluster's DNS zone
+
[source,bash]
----
for cname in "api" "apps"; do
  exo dns add CNAME "${CLUSTER_ID}.${BASE_DOMAIN}" -n "_acme-challenge.${cname}" -a "${fulldomain}." -t 600
done
----
endif::[]

=== Finalize installation

. Configure the apt-dater groups for the LBs.
+
[source,bash]
----
git clone git@git.vshn.net:vshn-puppet/nodes_hieradata.git
pushd nodes_hieradata
cat >"${LB_FQDNS[1]}.yaml" <<EOF
---
s_apt_dater::host::group: '2200_20_night_main'
EOF
cat >"${LB_FQDNS[2]}.yaml" <<EOF
---
s_apt_dater::host::group: '2200_40_night_second'
EOF
git add *.yaml
git commit -m"Configure apt-dater groups for LBs for OCP4 cluster ${CLUSTER_ID}"
git push origin master
popd
----
+
[NOTE]
====
This how-to defaults to the night maintenance window on Tuesday at 22:00.
Adjust the apt-dater groups according to the https://wiki.vshn.net/display/VT/Available+apt-dater+Groups[documented groups] (VSHN-internal only) if the cluster requires a different maintenance window.
====

. Wait for deploy job on nodes hieradata to complete and run Puppet on the LBs to update the apt-dater groups.
+
[source,bash]
----
for fqdn in "${LB_FQDNS[@]}"; do
  ssh "${fqdn}" sudo puppetctl run
done
----

. Delete local config files
+
[source,bash]
----
rm -r ${INSTALLER_DIR}/
----

=== Post tasks

. Doing a https://kb.vshn.ch/oc4/how-tos/update_maintenance.html[first maintenance]
. Add the cluster to the https://wiki.vshn.net/pages/templates2/editpagetemplate.action?entityId=137527297&key=VT[maintenance template]
