ifeval::["{provider}" == "cloudscale"]
:acme-dns-update-zone: yes
endif::[]
ifeval::["{provider}" == "openstack"]
:acme-dns-update-zone: yes
endif::[]

:dummy:
ifeval::["{provider}" == "vsphere"]
=== Set default storage class

. Set storage class `thin-csi` as default
+
[source,bash]
----
kubectl annotate storageclass thin storageclass.kubernetes.io/is-default-class-
kubectl annotate storageclass thin-csi storageclass.kubernetes.io/is-default-class=true
----

endif::[]

=== Enable Project Syn

. https://kb.vshn.ch/vshnsyn/how-tos/synthesize.html[Make the cluster Project Syn enabled]

=== Setup acme-dns CNAME records for the cluster

NOTE: You can skip this section if you're not using Let's Encrypt for the cluster's API and default wildcard certificates.

. Extract the acme-dns subdomain for the cluster after `cert-manager` has been deployed via Project Syn.
+
[source,bash]
----
fulldomain=$(kubectl -n syn-cert-manager \
  get secret acme-dns-client \
  -o jsonpath='{.data.acmedns\.json}' | \
  base64 -d  | \
  jq -r '[.[]][0].fulldomain')
echo "$fulldomain"
----

ifeval::["{acme-dns-update-zone}" == "yes"]
. Add the following CNAME records to the cluster's DNS zone
+
[IMPORTANT]
====
The `_acme-challenge` records must be created in the same zone as the cluster's `api` and `apps` records respectively.
====
+
[source,dns]
----
$ORIGIN <cluster-zone> <2>
_acme-challenge.api  IN CNAME <fulldomain>. <1>
$ORIGIN <apps-base-domain> <3>
_acme-challenge.apps IN CNAME <fulldomain>. <1>
----
<1> Replace `<fulldomain>` with the output of the previous step.
<2> The `_acme-challenge.api` record must be created in the same origin as the `api` record.
<3> The `_acme-challenge.apps` record must be created in the same origin as the `apps` record.
endif::[]
ifeval::["{provider}" == "exoscale"]
. Setup the `_acme-challenge` CNAME records in the cluster's DNS zone
+
[IMPORTANT]
====
The `_acme-challenge` records must be created in the same zone as the cluster's `api` and `apps` records respectively.
The snippet below assumes that the cluster is configured to use the default "apps" domain in the cluster's zone.
====
+
[source,bash]
----
for cname in "api" "apps"; do
  exo dns add CNAME "${CLUSTER_DOMAIN}" -n "_acme-challenge.${cname}" -a "${fulldomain}." -t 600
done
----
endif::[]

=== Store the cluster's admin credentials in the password manager

. Once the cluster's production API certificate has been deployed, edit the cluster's admin kubeconfig file to remove the initial API certificate CA.
+
[TIP]
====
You may see the error `Unable to connect to the server: x509: certificate signed by unknown authority` when executing `kubectl` or `oc` commands after the cluster's production API certificate has been deployed by Project Syn.

This error can be addressed by removing the initial CA certificate data from the admin kubeconfig as shown in this step.
====
+
[source,bash]
----
yq e -i 'del(.clusters[0].cluster.certificate-authority-data)' \
  "${INSTALLER_DIR}/auth/kubeconfig"
----

. Save the admin credentials in the https://cloud.passbolt.com/vshn[password manager].
You can find the password in the file `target/auth/kubeadmin-password` and the kubeconfig in `target/auth/kubeconfig`
+
[source,bash]
----
ls -l ${INSTALLER_DIR}/auth/
----
