. Switch to the tenant repo
+
[source,bash]
----
pushd "inventory/classes/${TENANT_ID}/"
----

. Include openshift4.yml if it exists
+
[source,bash]
----
if ls openshift4.y*ml 1>/dev/null 2>&1; then
    yq eval -i '.classes += ".openshift4"' ${CLUSTER_ID}.yml;
fi
----

. Update cluster config
+
[source,bash,subs="attributes+"]
----
yq eval -i ".parameters.openshift.baseDomain = \"${CLUSTER_DOMAIN}\"" \
  ${CLUSTER_ID}.yml

yq eval -i ".parameters.openshift.infraID = \"$(jq -r .infraID "${INSTALLER_DIR}/metadata.json")\"" \
  ${CLUSTER_ID}.yml

yq eval -i ".parameters.openshift.clusterID = \"$(jq -r .clusterID "${INSTALLER_DIR}/metadata.json")\"" \
  ${CLUSTER_ID}.yml

yq eval -i ".parameters.openshift.ssh_key = \"$(cat ${SSH_PUBLIC_KEY})\"" \
  ${CLUSTER_ID}.yml

yq eval -i ".parameters.vshnLdap.serviceId = \"${LDAP_ID}\"" \
  ${CLUSTER_ID}.yml
----
+
[NOTE]
====
If you use a custom "apps" domain, make sure to set `parameters.openshift.appsDomain` accordingly.

[source,bash]
----
APPS_DOMAIN=your.custom.apps.domain
yq eval -i ".parameters.openshift.appsDomain = \"${APPS_DOMAIN}\"" \
  ${CLUSTER_ID}.yml
----
====
+
[TIP]
====
By default, the cluster's update channel is derived from the cluster's reported OpenShift version.
If you want to use a custom update channel, make sure to set `parameters.openshift4_version.spec.channel` accordingly.

[source,bash]
----
# Configure the OpenShift update channel as `fast`
yq eval -i ".parameters.openshift4_version.spec.channel = \"fast-{ocp-minor-version}\"" \
  ${CLUSTER_ID}.yml
----
====


ifeval::["{provider}" != "vsphere"]
include::partial$install/prepare-syn-config-terraform.adoc[]
endif::[]
ifeval::["{provider}" == "vsphere"]
include::partial$install/prepare-syn-config-vsphere.adoc[]
endif::[]

ifeval::["{provider}" != "vsphere"]
[TIP]
====
You now have the option to further customize the cluster by editing `terraform_variables`.
Most importantly you have the option to change node sizes or add additional specialized worker nodes.

Please look at the xref:oc4:ROOT:references/{provider}/config.adoc[configuration reference] for the available options.
====
endif::[]

[#_compile_catalog]
=== Commit changes and compile cluster catalog

. Review changes.
Have a look at the file `${CLUSTER_ID}.yml`.
Override default parameters or add more component configurations as required for your cluster.
ifeval::["{provider}" == "exoscale"]
+
[IMPORTANT]
====
Ensure that you're using component `openshift4-terraform` v5.0.0 or newer.
Otherwise the instructions in this how-to might not apply.
====
endif::[]

. Commit changes
+
[source,bash]
----
git commit -a -m "Setup cluster ${CLUSTER_ID}"
git push

popd
----

. Compile and push cluster catalog
+
include::partial$install/commodore-dynfacts.adoc[]
