=== Prepare Cluster Repository

[TIP]
====
Starting with this section, we recommend that you change into a clean directory (for example a directory in your home).
====

[NOTE]
====
Check https://syn.tools/commodore/running-commodore.html[Running Commodore] for details on how to run commodore.
====

. Prepare Commodore inventory.
+
[source,bash]
----
mkdir -p inventory/classes/
git clone $(curl -sH"Authorization: Bearer $(commodore fetch-token)" "${COMMODORE_API_URL}/tenants/${TENANT_ID}" | jq -r '.gitRepo.url') inventory/classes/${TENANT_ID}
----

. Configure the cluster's domain in Project Syn
+
[source,bash]
----
export CLUSTER_DOMAIN="${CLUSTER_ID}.${BASE_DOMAIN}" <1>
----
<1> Adjust this as necessary if you're using a non-standard cluster domain.
+
[IMPORTANT]
====
The cluster domain configured here must be correct.
The value is used to configure how Cilium connects to the cluster's K8s API.
====
+
[source,bash]
----
pushd "inventory/classes/${TENANT_ID}/"

yq eval -i ".parameters.openshift.baseDomain = \"${CLUSTER_DOMAIN}\"" \
  ${CLUSTER_ID}.yml

git commit -a -m "Configure cluster domain for ${CLUSTER_ID}"
----

. Include `openshift4.yml` in the cluster's config if it exists
+
NOTE: For some tenants, this may already configure some of the settings shown in this how-to.
+
[source,bash]
----
if ls openshift4.y*ml 1>/dev/null 2>&1; then
    yq eval -i '.classes += ".openshift4"' ${CLUSTER_ID}.yml;
    git commit -a -m "Include openshift4 class for ${CLUSTER_ID}"
fi
----

ifeval::["{provider}" == "exoscale"]
. Include the Exoscale cloud-controller-manager Commodore component
+
[source,bash]
----
yq eval -i '.applications += "exoscale-cloud-controller-manager"' ${CLUSTER_ID}.yml
git commit -a -m "Deploy Exoscale cloud-controller-manager on ${CLUSTER_ID}"
----
endif::[]

. Add Cilium to cluster configuration
+
[NOTE]
====
These instructions assume that Cilium is configured to use `api-int.${CLUSTER_DOMAIN}:6443` to connect to the cluster's K8s API.
To ensure that that's the case, add the configuration shown below somewhere in the Project Syn config hierarchy.

[source,yaml]
----
parameters:
  cilium:
    cilium_helm_values:
      k8sServiceHost: api-int.${openshift:baseDomain}
      k8sServicePort: "6443"
----

For VSHN, this configuration is set in the https://git.vshn.net/syn/commodore-defaults/-/merge_requests/1789[Commodore global defaults (internal)].
====
+
[NOTE]
====
If you have a non-standard pod network, you need to ensure to include this in the configuration.

[source,yaml]
----
parameters:
  cilium:
    cilium_helm_values:
      ipam:
        operator:
          ~clusterPoolIPv4PodCIDRList:
            - <POD_NETWORK_CIDR>
----
====
+
[source,bash]
----
yq eval -i '.applications += ["cilium"]' ${CLUSTER_ID}.yml

yq eval -i '.parameters.networkpolicy.networkPlugin = "cilium"' ${CLUSTER_ID}.yml
yq eval -i '.parameters.networkpolicy.ignoredNamespaces = ["openshift-oauth-apiserver"]' ${CLUSTER_ID}.yml

yq eval -i '.parameters.openshift4_monitoring.upstreamRules.networkPlugin = "cilium"' ${CLUSTER_ID}.yml

yq eval -i '.parameters.openshift.infraID = "TO_BE_DEFINED"' ${CLUSTER_ID}.yml
yq eval -i '.parameters.openshift.clusterID = "TO_BE_DEFINED"' ${CLUSTER_ID}.yml

git commit -a -m "Add Cilium addon to ${CLUSTER_ID}"

git push
popd
----

. Compile catalog
+
include::partial$install/commodore-dynfacts.adoc[]
