. Switch to the tenant repo
+
[source,bash]
----
pushd "inventory/classes/${TENANT_ID}/"
----

. Include no-opsgenie class to prevent monitoring noise during cluster setup
+
[source,bash]
----
yq eval -i '.classes += "global.distribution.openshift4.no-opsgenie"' ${CLUSTER_ID}.yml;
----

. Update cluster config
+
[source,bash,subs="attributes+"]
----
yq eval -i ".parameters.openshift.infraID = \"$(jq -r .infraID "${INSTALLER_DIR}/metadata.json")\"" \
  ${CLUSTER_ID}.yml

yq eval -i ".parameters.openshift.clusterID = \"$(jq -r .clusterID "${INSTALLER_DIR}/metadata.json")\"" \
  ${CLUSTER_ID}.yml

yq eval -i ".parameters.openshift.ssh_key = \"$(cat ${SSH_PUBLIC_KEY})\"" \
  ${CLUSTER_ID}.yml
----
+
[NOTE]
====
If you use a custom "apps" domain, make sure to set `parameters.openshift.appsDomain` accordingly.

[source,bash]
----
APPS_DOMAIN=your.custom.apps.domain
yq eval -i ".parameters.openshift.appsDomain = \"${APPS_DOMAIN}\"" \
  ${CLUSTER_ID}.yml
----
====
+
[TIP]
====
By default, the cluster's update channel is derived from the cluster's reported OpenShift version.
If you want to use a custom update channel, make sure to set `parameters.openshift4_version.spec.channel` accordingly.

[source,bash]
----
# Configure the OpenShift update channel as `fast`
yq eval -i ".parameters.openshift4_version.spec.channel = \"fast-{ocp-minor-version}\"" \
  ${CLUSTER_ID}.yml
----
====

. Enable AppCat if required
+
[source,bash]
----
yq eval -i ".classes += \".global.apps.appcat\"" \
  ${CLUSTER_ID}.yml
----
+
[NOTE]
====
AppCat requires extra resources on the master nodes.
Please ensure the master sizing is at least 8 CPU / 32 GB RAM.
====

ifeval::["{provider}" == "cloudscale"]
:is-terraform: yes
endif::[]
ifeval::["{provider}" == "exoscale"]
:is-terraform: yes
endif::[]
ifeval::["{provider}" == "stackit"]
:is-terraform: yes
endif::[]

ifeval::["{is-terraform}" == "yes"]
include::partial$install/prepare-syn-config-terraform.adoc[]
endif::[]
ifeval::["{provider}" == "vsphere"]
include::partial$install/prepare-syn-config-vsphere.adoc[]
endif::[]
ifeval::["{provider}" == "openstack"]
include::partial$install/prepare-syn-config-openstack.adoc[]
endif::[]

ifeval::["{is-terraform}" == "yes"]
[TIP]
====
You now have the option to further customize the cluster by editing `terraform_variables`.
Most importantly you have the option to change node sizes or add additional specialized worker nodes.

Please look at the xref:oc4:ROOT:references/{provider}/config.adoc[configuration reference] for the available options.
====

[NOTE]
====
AppCat requires extra resources on the master nodes.
If AppCat is enabled, please ensure the master sizing is at least 8 CPU / 32 GB RAM.
====
endif::[]

[#_compile_catalog]
=== Commit changes and compile cluster catalog

ifeval::["{provider}" == "vsphere"]
:manage-https-proxy: yes
endif::[]
ifeval::["{provider}" == "openstack"]
:manage-https-proxy: yes
endif::[]

. Review changes.
Have a look at the file `${CLUSTER_ID}.yml`.
Override default parameters or add more component configurations as required for your cluster.
ifeval::["{provider}" == "exoscale"]
+
[IMPORTANT]
====
Ensure that you're using component `openshift4-terraform` v7.0.0 or newer.
Otherwise the instructions in this how-to might not apply.
====
endif::[]

. Commit changes
+
[source,bash]
----
git commit -a -m "Setup cluster ${CLUSTER_ID}"
git push

popd
----

ifeval::["{manage-https-proxy}" == "yes"]
. Temporarily unset `https_proxy` since Commodore currently doesn't support `https_proxy`
+
[source,bash]
----
https_proxy_bak=$https_proxy
unset https_proxy
----
+
TIP: You can skip this step and "Restore https_proxy" if you're not using a HTTPS proxy for the installation.
endif::[]

. Compile and push cluster catalog
+
include::partial$install/commodore-dynfacts.adoc[]

ifeval::["{manage-https-proxy}" == "yes"]
. Restore `https_proxy`
+
[source,bash]
----
export https_proxy=$https_proxy_bak
----
endif::[]
