Register the new OpenShift 4 cluster in Lieutenant.

.Lieutenant API endpoint
****
Use the following endpoint for Lieutenant:

VSHN:: https://api.syn.vshn.net
****

=== Set cluster facts
For customer clusters, set the following cluster facts in Lieutenant:

* `sales_order`: Name of the sales order to which the cluster is billed, such as `S10000`
* `service_level`: Name of the service level agreement for this cluster, such as `guaranteed-availability`
* `access_policy`: Access-Policy of the cluster, such as `regular` or `swissonly`
* `release_channel`: Name of the syn component release channel to use, such as `stable`
* `maintenance_window`: Pick the appropriate https://git.vshn.net/syn/commodore-defaults/-/tree/master/distribution/openshift4/managed-upgrade-schedules[upgrade schedule], such as `monday-1400` for test clusters, `tuesday-1000` for prod or `custom` to not (yet) enable maintenance
* `cilium_addons`: Comma-separated list of cilium addons the customer gets billed for, such as `advanced_networking` or `tetragon`. Set to `NONE` if no addons should be billed.

=== Set up Keycloak service

. Create a Keycloak service
+
Use https://control.vshn.net/vshn/services/_create to create a service.
The name and ID must be clusters name.
For the optional URL use the OpenShift console URL.
