[CAUTION]
The steps in this section aren't idempotent and have to be completed uninterrupted in one go.
If you have to recreate the install config or any of the generated manifests you need to rerun all of the subsequent steps.

. Render install manifests (this will consume the `install-config.yaml`)
+
[source,bash]
----
openshift-install --dir "${INSTALLER_DIR}" \
  create manifests
----
ifeval::["{provider}" == "vsphere"]
+
[IMPORTANT]
====
If this step prints `WARNING unable to resolve vSphere server <vcenter hostname>`, please make sure that `dig +short ${VCENTER_HOSTNAME}` returns an IP on the host where you're running `openshift-install`.

If you ignore this warning, `openshift-install create cluster` will not create the bootstrap and control-plane nodes.
====
endif::[]

.. If you want to change the default "apps" domain for the cluster:
+
[source,bash]
----
yq w -i "${INSTALLER_DIR}/manifests/cluster-ingress-02-config.yml" \
  spec.domain apps.example.com
----

. Copy pre-rendered extra machine configs
+
[source,bash]
----
machineconfigs=catalog/manifests/openshift4-nodes/10_machineconfigs.yaml
if [ -f $machineconfigs ];  then
  yq --no-doc -s \
    "\"${INSTALLER_DIR}/openshift/99x_openshift-machineconfig_\" + .metadata.name" \
    $machineconfigs
fi
----

ifeval::["{provider}" == "cloudscale"]
. Copy cloud-controller-manager manifests
+
[TIP]
====
This step assumes that component https://github.com/projectsyn/component-cloudscale-cloud-controller-manager/releases/tag/v1.3.0[cloudscale-cloud-controller-manager v1.3.0] or newer is used.
====
+
[source,bash]
----
for f in catalog/manifests/cloudscale-cloud-controller-manager/*; do
  cp $f ${INSTALLER_DIR}/manifests/cloudscale_ccm_$(basename $f)
done
yq -i e ".stringData.access-token=\"${CLOUDSCALE_API_TOKEN}\"" \
  ${INSTALLER_DIR}/manifests/cloudscale-cloud-controller-manager_01_secret_0_secret.yml
----
endif::[]
ifeval::["{provider}" == "exoscale"]
. Copy cloud-controller-manager manifests
+
[source,bash,]
----
for f in catalog/manifests/exoscale-cloud-controller-manager/manager/*; do
  cp $f ${INSTALLER_DIR}/manifests/exoscale_ccm_$(basename $f)
done

yq -i e ".stringData.api-key=\"${CCM_ACCESSKEY}\",.stringData.api-secret=\"${CCM_SECRETKEY}\"" \
  ${INSTALLER_DIR}/manifests/exoscale_ccm_01_secret.yaml
----
endif::[]

. Copy pre-rendered Cilium manifests
+
[source,bash]
----
cp catalog/manifests/cilium/olm/* ${INSTALLER_DIR}/manifests/
----

. Verify that the generated cluster domain matches the desired cluster domain
+
[source,bash]
----
GEN_CLUSTER_DOMAIN=$(yq e '.spec.baseDomain' \
  "${INSTALLER_DIR}/manifests/cluster-dns-02-config.yml")
if [ "$GEN_CLUSTER_DOMAIN" != "$CLUSTER_DOMAIN" ]; then
  echo -e "\033[0;31mGenerated cluster domain doesn't match expected cluster domain: Got '$GEN_CLUSTER_DOMAIN', want '$CLUSTER_DOMAIN'\033[0;0m"
else
  echo -e "\033[0;32mGenerated cluster domain matches expected cluster domain.\033[0;0m"
fi
----

. Prepare install manifests and ignition config
+
[source,bash]
----
openshift-install --dir "${INSTALLER_DIR}" \
  create ignition-configs
----
