= Installation on Google Cloud Platform

:toc:


== General Procedure

. Setup GCP project

  * DNS zone
  * Service Account

. Cluster setup

  * prepare installer configuration
  * run installer

. Synfection

. Post install configuration

== Configure the GCP Project

//https://docs.openshift.com/container-platform/4.4/installing/installing_gcp/installing-gcp-account.html


.Required input
`<base domain>`:: The base domain used to make the cluster accessible.
`<cluster name>`::
The name of the cluster.
This name will be used as identifier or as part of identifiers.
It also will become a subdomain to the base domain.
`<project name>`:: The name of the GCP project.

[CAUTION]
====
If the project and region names are too long, node provisioning will not work.
See xref:explanations/gcp/name_lengths.adoc[Name length on GCP].
====

. Enable services
+
[source,bash]
----
gcloud services enable \
  compute.googleapis.com \
  cloudapis.googleapis.com \
  cloudresourcemanager.googleapis.com \
  dns.googleapis.com \
  iamcredentials.googleapis.com \
  iam.googleapis.com \
  servicemanagement.googleapis.com \
  serviceusage.googleapis.com \
  storage-api.googleapis.com \
  storage-component.googleapis.com
----

. Create DNS zone
+
[source,bash]
----
gcloud dns managed-zones create <zone name> \ <1>
  --dns-name=<base domain> \ <2>
  --description="<zone description>"` <3>
----
<1> Name used within GCP to identify/address the zone.
<2> The base domain from the inputs above.
<3> Short description to give humans more context about the zone.

. Extract name servers and ensure domain gets properly delegated at the registrar or the parent zone
+
[source,bash]
----
gcloud dns managed-zones describe <zone name> --format json | jq -r '.nameServers[]' <1>
----
<1> Zone name used when creating the zone

. Check GCP account limits
+
For region `europe-west6` (Zürich), CPU quota might be too low.
Other regions are also affected (see https://docs.openshift.com/container-platform/4.4/installing/installing_gcp/installing-gcp-account.html#installation-gcp-limits_installing-gcp-account)
+  
For the other regions, the default account quotas are sufficient for an OpenShift cluster.
This might not be the case when using an account already containing resources.
+
Raising quotas can be done at https://console.cloud.google.com/iam-admin/quotas.
+  
NOTE: Plan ahead as this can take up to two days. It usually takes only seconds though.
+
[TIP]
====
Use the https://access.redhat.com/labs/ocplimitscalculator/[OpenShift Limits Calculator] to calculate your needs.
This is especially handy when it is planned to setup several clusters within one project.
It does not take regions into consideration and some regions have different defaults.
Take the column "Service Limit increase necessary?" with a grain of salt and double check.
====

. Create a GCP service account
+
[source,bash]
----
gcloud iam service-accounts create openshift4-installer-<cluster name> \ <1>
  --display-name="OpenShift 4 Installer of cluster `<cluster name>`" <1>
----
<1> Use cluster name from the inputs.
+
And give it the required permissions:
+
[source,bash]
----
read -d '' roles <<EOF
roles/compute.admin
roles/iam.securityAdmin
roles/iam.serviceAccountAdmin
roles/iam.serviceAccountKeyAdmin
roles/iam.serviceAccountUser
roles/storage.admin
roles/dns.admin
EOF

while IFS= read -r role; do
  gcloud projects add-iam-policy-binding <project name> \ <1>
    --member serviceAccount:openshift4-installer-<cluster name>@<project name>.iam.gserviceaccount.com \ <2>
    --role="${role}"
done <<< ${roles}
----
<1> The project name from the inputs.
<2> The cluster name from the inputs. The service account email must match the one previously created.
+
[NOTE]
====
The documentation suggests to give the Service Account the `roles/owner` role.
It also gives advice which roles to use if one does want to work with less privileges.
The given list might not be complete or is ambiguous (name vs description).
The first attempt with the above role set failed.
The worker nodes did not come up.
====

. Create Service Account Key [[service-account-key]]
+
[source,bash]
----
gcloud iam service-accounts keys create key.json \
  --iam-account openshift4-installer-<cluster name>@<project name>.iam.gserviceaccount.com <1>
----
<1> The cluster name from the inputs. The service account email must match the one previously created.

. Ensure firewall settings
+
By default, no firewall is configured within a project.
When using a project created by a third party, we need to check if the firewall settings meet the requirements from https://docs.openshift.com/container-platform/4.4/installing/install_config/configuring-firewall.html#configuring-firewall.

== Create installer configuration

Prerequisites:
* GCP project setup according to above documentation
* Service Account Key (key.json)

TIP: https://github.com/projectsyn/purser[Purser] can be used to check if the preconditons are met.

.Required input
`<base domain>`:: The base domain used to make the cluster available.
`<cluster name>`::
The name of the cluster.
This name will be used as identifier or as part of identifiers.
It also will become a subdomain to the base domain.
`<service account key>`:: See <<service-account-key>> 
`<region>`:: The GCP region to place the cluster. Default to `europe-west6`

. Obtain the installer and pull secret

   * https://cloud.redhat.com/openshift/install/gcp/installer-provisioned
   * https://cloud.redhat.com/openshift/install/pull-secret

. Copy `<service account key>` to `~/.gcp/osServiceAccount.json`

. Create an SSH key for that cluster
+
[source,bash]
----
ssh-keygen -t rsa -b 4096 -N '' -f ~/.ssh/<cluster name> -C <cluster name>
----
+
NOTE: The key must be within the home directory to be picked up by the installer.

. Create the default installer config
+
[source,bash]
----
openshift-install create install-config --dir=<cluster name>-config <1>
----
<1> The cluster name from the inputs.
+
--
.Answers
SSH Public Key:: `~/.ssh/<cluster namme>`
Platform:: gcp
Project ID:: Will be extracted from the service account key file.
Region:: <region>
Base Domain:: <base domain>
Cluster Name:: <cluster name>
Pull Secret:: Grab from https://cloud.redhat.com/openshift/install/pull-secret.
--
+
.Credentials for Pull Secret
****
If the customer brings his own subscriptions, the customer should obtain the Pull Secret using his Red Hat account and produce us the Pull Secret.

For all the other cases:

VSHN:: https://password.vshn.net/cred/detail/2420/
****

. Review and tweak installer config
+
Use your editor of choice to review the created installer config.
Make changes where required.

. Make a copy of the installer config
+
Once the installer gets executed, the config will be consumed and deleted.
If the installer fails and another attempt must be made, a copy of the config is a good thing to have.
+
[source,bash]
----
cp -r <cluster name>-config <cluster name>
----

. Run the installer
+
[source,bash]
----
openshift-install create cluster --log-level=debug --dir=<cluster name>
----
+  
[WARNING]
====
Takes roughly 45 minutes to complete.
The installer might timeout.
This does not necessarily indicate a failed setup.
Waiting some more time might be enough.
====
   
. Put the `kubeadmin` credentials into password manager
+
Create a new password record.
Use `kubeadmin` as username and the password from `<cluster name>/auth/kubeadmin-password`.
Also upload `<cluster name>/auth/kubeconfig` as an attachment.
+  
.Password manager
****
VSHN:: Use https://password.vshn.net
****

. Gain access to the OpenShift/Kubernetes API
+
[source,bash]
----
export KUBECONFIG=<cluster name>/auth/kubeconfig
----

. Synfection
+
Synfect the cluster according to https://wiki.vshn.net/x/ngMBCg.
